export const ROLES = {
  STAFF: 'staff',
  MANAGER: 'manager',
  ADMIN: 'admin',
} as const;

export const PERMISSIONS = {
  // Orders
  VIEW_MY_ORDERS: 'orders.view_own',
  VIEW_ALL_ORDERS: 'orders.view_all',
  CREATE_ORDER: 'orders.create',
  UPDATE_ORDER: 'orders.update',
  DELETE_ORDER: 'orders.delete',
  ASSIGN_ORDER: 'orders.assign',
  
  // POS
  ACCESS_POS: 'pos.access',
  SCAN_BARCODE: 'pos.scan_barcode',
  PROCESS_PAYMENT: 'pos.process_payment',
  OPEN_CLOSE_SHIFT: 'pos.open_close_shift',
  
  // Inventory
  VIEW_INVENTORY: 'inventory.view',
  MANAGE_INVENTORY: 'inventory.manage',
  TRANSFER_STOCK: 'inventory.transfer',
  ADJUST_STOCK: 'inventory.adjust',
  
  // Staff Management
  VIEW_STAFF: 'users.view_all',
  MANAGE_STAFF: 'users.manage',
  ASSIGN_TASKS: 'tasks.assign',
  VIEW_PERFORMANCE: 'analytics.view_staff_reports',
  
  // Tasks
  VIEW_OWN_TASKS: 'tasks.view_own',
  VIEW_ALL_TASKS: 'tasks.view_all',
  CREATE_TASKS: 'tasks.create',
  
  // Analytics & Reports
  VIEW_ANALYTICS: 'analytics.view_store_dashboard',
  EXPORT_REPORTS: 'analytics.export_reports',
  SCHEDULE_REPORTS: 'analytics.schedule_reports',
  
  // CRM
  VIEW_CRM: 'crm.view',
  EDIT_CRM: 'crm.edit',
  CREATE_CRM_INTERACTIONS: 'crm.create_interactions',
  VIEW_CRM_ANALYTICS: 'crm.view_analytics',
  
  // LRM
  VIEW_LRM: 'lrm.view',
  EDIT_LRM: 'lrm.edit',
  MANAGE_SUPPLIERS: 'lrm.manage_suppliers',
  REQUEST_TRANSFERS: 'lrm.request_transfers',
  CONFIRM_DELIVERIES: 'lrm.confirm_deliveries',
  
  // HRM
  VIEW_OWN_HRM: 'hrm.view_own',
  VIEW_ALL_HRM: 'hrm.view_all',
  MANAGE_HRM: 'hrm.manage',
  SUBMIT_LEAVE_REQUESTS: 'hrm.submit_leave_requests',
  APPROVE_LEAVE_REQUESTS: 'hrm.approve_leave_requests',
  ASSIGN_SHIFTS: 'hrm.assign_shifts',
  
  // System
  MANAGE_SETTINGS: 'system.manage_settings',
  VIEW_AUDIT_LOG: 'system.view_audit_log',
  SEND_BROADCAST: 'system.send_broadcast',
  
  // Admin
  MANAGE_USERS: 'admin.manage_users',
  MANAGE_ROLES: 'admin.manage_roles',
  MANAGE_PERMISSIONS: 'admin.manage_permissions',
  SYSTEM_CONFIGURATION: 'admin.system_configuration',
  DATABASE_BACKUP: 'admin.database_backup',
  SYSTEM_MONITOR: 'admin.system_monitor',
  MANAGE_STORES: 'admin.manage_stores',
  VIEW_ALL_ANALYTICS: 'admin.view_all_analytics',
  SUPER_ADMIN: 'admin.super_admin',
} as const;

export const ROLE_PERMISSIONS = {
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_MY_ORDERS,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.ACCESS_POS,
    PERMISSIONS.SCAN_BARCODE,
    PERMISSIONS.PROCESS_PAYMENT,
    PERMISSIONS.OPEN_CLOSE_SHIFT,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_OWN_TASKS,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.VIEW_LRM,
    PERMISSIONS.CONFIRM_DELIVERIES,
    PERMISSIONS.VIEW_OWN_HRM,
    PERMISSIONS.SUBMIT_LEAVE_REQUESTS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_MY_ORDERS,
    PERMISSIONS.VIEW_ALL_ORDERS,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.DELETE_ORDER,
    PERMISSIONS.ASSIGN_ORDER,
    PERMISSIONS.ACCESS_POS,
    PERMISSIONS.SCAN_BARCODE,
    PERMISSIONS.PROCESS_PAYMENT,
    PERMISSIONS.OPEN_CLOSE_SHIFT,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.TRANSFER_STOCK,
    PERMISSIONS.ADJUST_STOCK,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.VIEW_OWN_TASKS,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.VIEW_PERFORMANCE,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.SCHEDULE_REPORTS,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.EDIT_CRM,
    PERMISSIONS.CREATE_CRM_INTERACTIONS,
    PERMISSIONS.VIEW_CRM_ANALYTICS,
    PERMISSIONS.VIEW_LRM,
    PERMISSIONS.EDIT_LRM,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.REQUEST_TRANSFERS,
    PERMISSIONS.CONFIRM_DELIVERIES,
    PERMISSIONS.VIEW_ALL_HRM,
    PERMISSIONS.MANAGE_HRM,
    PERMISSIONS.APPROVE_LEAVE_REQUESTS,
    PERMISSIONS.ASSIGN_SHIFTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.SEND_BROADCAST,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_MY_ORDERS,
    PERMISSIONS.VIEW_ALL_ORDERS,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.DELETE_ORDER,
    PERMISSIONS.ASSIGN_ORDER,
    PERMISSIONS.ACCESS_POS,
    PERMISSIONS.SCAN_BARCODE,
    PERMISSIONS.PROCESS_PAYMENT,
    PERMISSIONS.OPEN_CLOSE_SHIFT,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.TRANSFER_STOCK,
    PERMISSIONS.ADJUST_STOCK,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.VIEW_OWN_TASKS,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.VIEW_PERFORMANCE,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.SCHEDULE_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.SEND_BROADCAST,
    
    // CRM, LRM, HRM
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.EDIT_CRM,
    PERMISSIONS.CREATE_CRM_INTERACTIONS,
    PERMISSIONS.VIEW_CRM_ANALYTICS,
    PERMISSIONS.VIEW_LRM,
    PERMISSIONS.EDIT_LRM,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.REQUEST_TRANSFERS,
    PERMISSIONS.CONFIRM_DELIVERIES,
    PERMISSIONS.VIEW_ALL_HRM,
    PERMISSIONS.MANAGE_HRM,
    PERMISSIONS.APPROVE_LEAVE_REQUESTS,
    PERMISSIONS.ASSIGN_SHIFTS,
    PERMISSIONS.VIEW_OWN_HRM,
    PERMISSIONS.SUBMIT_LEAVE_REQUESTS,
    
    // Admin permissions
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_PERMISSIONS,
    PERMISSIONS.SYSTEM_CONFIGURATION,
    PERMISSIONS.DATABASE_BACKUP,
    PERMISSIONS.SYSTEM_MONITOR,
    PERMISSIONS.MANAGE_STORES,
    PERMISSIONS.VIEW_ALL_ANALYTICS,
    PERMISSIONS.SUPER_ADMIN,
  ],
};

export const LANGUAGES = {
  EN: 'en',
  VI: 'vi',
} as const;

export const THEMES = {
  LIGHT: 'light',
  DARK: 'dark',
} as const;

export const ORDER_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  REFUNDED: 'refunded',
} as const;

export const PAYMENT_METHOD = {
  CASH: 'cash',
  CARD: 'card',
  DIGITAL: 'digital',
} as const;

export const NOTIFICATION_TYPES = {
  ORDER: 'order',
  INVENTORY: 'inventory',
  STAFF: 'staff',
  SYSTEM: 'system',
} as const;