/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseBoolean,
  ApiResponseInt32,
  ApiResponseListProductsProductListDto,
  ApiResponsePaginatedResultProductsProductListDto,
  ApiResponseProductsProductDetailDto,
  GetApiProductParams,
  GetApiV1ProductParams,
  MicrosoftAspNetCoreMvcProblemDetails,
  ProductsProductCreateDto,
  ProductsProductUpdateDto
} from '.././schemas';

import { apiClient } from '../../../src/lib/api/orval-client';




export const postApiProduct = (
    productsProductCreateDto: ProductsProductCreateDto,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/Product`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productsProductCreateDto, signal
    },
      );
    }
  


export const getPostApiProductMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProduct>>, TError,{data: ProductsProductCreateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiProduct>>, TError,{data: ProductsProductCreateDto}, TContext> => {

const mutationKey = ['postApiProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProduct>>, {data: ProductsProductCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiProduct(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiProductMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProduct>>>
    export type PostApiProductMutationBody = ProductsProductCreateDto
    export type PostApiProductMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePostApiProduct = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProduct>>, TError,{data: ProductsProductCreateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProduct>>,
        TError,
        {data: ProductsProductCreateDto},
        TContext
      > => {

      const mutationOptions = getPostApiProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiProduct = (
    params?: GetApiProductParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResultProductsProductListDto>(
      {url: `/api/Product`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiProductQueryKey = (params?: GetApiProductParams,) => {
    return [
    `/api/Product`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiProductQueryOptions = <TData = Awaited<ReturnType<typeof getApiProduct>>, TError = unknown>(params?: GetApiProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProduct>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProduct>>> = ({ signal }) => getApiProduct(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProduct>>>
export type GetApiProductQueryError = unknown


export function useGetApiProduct<TData = Awaited<ReturnType<typeof getApiProduct>>, TError = unknown>(
 params: undefined |  GetApiProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProduct>>,
          TError,
          Awaited<ReturnType<typeof getApiProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProduct<TData = Awaited<ReturnType<typeof getApiProduct>>, TError = unknown>(
 params?: GetApiProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProduct>>,
          TError,
          Awaited<ReturnType<typeof getApiProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProduct<TData = Awaited<ReturnType<typeof getApiProduct>>, TError = unknown>(
 params?: GetApiProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProduct>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProduct<TData = Awaited<ReturnType<typeof getApiProduct>>, TError = unknown>(
 params?: GetApiProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProduct>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiProductId = (
    id: string,
    productsProductUpdateDto: ProductsProductUpdateDto,
 ) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/Product/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: productsProductUpdateDto
    },
      );
    }
  


export const getPutApiProductIdMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProductId>>, TError,{id: string;data: ProductsProductUpdateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiProductId>>, TError,{id: string;data: ProductsProductUpdateDto}, TContext> => {

const mutationKey = ['putApiProductId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiProductId>>, {id: string;data: ProductsProductUpdateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiProductId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiProductId>>>
    export type PutApiProductIdMutationBody = ProductsProductUpdateDto
    export type PutApiProductIdMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePutApiProductId = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProductId>>, TError,{id: string;data: ProductsProductUpdateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiProductId>>,
        TError,
        {id: string;data: ProductsProductUpdateDto},
        TContext
      > => {

      const mutationOptions = getPutApiProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiProductId = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Product/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiProductIdMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiProductId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiProductId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiProductId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiProductId>>>
    
    export type DeleteApiProductIdMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const useDeleteApiProductId = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiProductId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiProductId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/Product/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiProductIdQueryKey = (id?: string,) => {
    return [
    `/api/Product/${id}`
    ] as const;
    }

    
export const getGetApiProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductId>>> = ({ signal }) => getApiProductId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductId>>>
export type GetApiProductIdQueryError = MicrosoftAspNetCoreMvcProblemDetails


export function useGetApiProductId<TData = Awaited<ReturnType<typeof getApiProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductId<TData = Awaited<ReturnType<typeof getApiProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductId<TData = Awaited<ReturnType<typeof getApiProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductId<TData = Awaited<ReturnType<typeof getApiProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiProductIdActive = (
    id: string,
    boolean: boolean,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Product/${id}/active`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: boolean
    },
      );
    }
  


export const getPatchApiProductIdActiveMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdActive>>, TError,{id: string;data: boolean}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdActive>>, TError,{id: string;data: boolean}, TContext> => {

const mutationKey = ['patchApiProductIdActive'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiProductIdActive>>, {id: string;data: boolean}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiProductIdActive(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiProductIdActiveMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiProductIdActive>>>
    export type PatchApiProductIdActiveMutationBody = boolean
    export type PatchApiProductIdActiveMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePatchApiProductIdActive = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdActive>>, TError,{id: string;data: boolean}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiProductIdActive>>,
        TError,
        {id: string;data: boolean},
        TContext
      > => {

      const mutationOptions = getPatchApiProductIdActiveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiProductIdFavorite = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Product/${id}/favorite`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiProductIdFavoriteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProductIdFavorite>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiProductIdFavorite>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiProductIdFavorite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProductIdFavorite>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiProductIdFavorite(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiProductIdFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProductIdFavorite>>>
    
    export type PostApiProductIdFavoriteMutationError = unknown

    export const usePostApiProductIdFavorite = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProductIdFavorite>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProductIdFavorite>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiProductIdFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchApiProductIdFeatured = (
    id: string,
    boolean: boolean,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Product/${id}/featured`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: boolean
    },
      );
    }
  


export const getPatchApiProductIdFeaturedMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdFeatured>>, TError,{id: string;data: boolean}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdFeatured>>, TError,{id: string;data: boolean}, TContext> => {

const mutationKey = ['patchApiProductIdFeatured'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiProductIdFeatured>>, {id: string;data: boolean}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiProductIdFeatured(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiProductIdFeaturedMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiProductIdFeatured>>>
    export type PatchApiProductIdFeaturedMutationBody = boolean
    export type PatchApiProductIdFeaturedMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePatchApiProductIdFeatured = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdFeatured>>, TError,{id: string;data: boolean}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiProductIdFeatured>>,
        TError,
        {id: string;data: boolean},
        TContext
      > => {

      const mutationOptions = getPatchApiProductIdFeaturedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchApiProductIdStock = (
    id: string,
    patchApiProductIdStockBody: number,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Product/${id}/stock`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiProductIdStockBody
    },
      );
    }
  


export const getPatchApiProductIdStockMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdStock>>, TError,{id: string;data: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdStock>>, TError,{id: string;data: number}, TContext> => {

const mutationKey = ['patchApiProductIdStock'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiProductIdStock>>, {id: string;data: number}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiProductIdStock(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiProductIdStockMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiProductIdStock>>>
    export type PatchApiProductIdStockMutationBody = number
    export type PatchApiProductIdStockMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePatchApiProductIdStock = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProductIdStock>>, TError,{id: string;data: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiProductIdStock>>,
        TError,
        {id: string;data: number},
        TContext
      > => {

      const mutationOptions = getPatchApiProductIdStockMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiProductIdStock = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseInt32>(
      {url: `/api/Product/${id}/stock`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiProductIdStockQueryKey = (id?: string,) => {
    return [
    `/api/Product/${id}/stock`
    ] as const;
    }

    
export const getGetApiProductIdStockQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductIdStock>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductIdStock>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductIdStockQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductIdStock>>> = ({ signal }) => getApiProductIdStock(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductIdStock>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductIdStockQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductIdStock>>>
export type GetApiProductIdStockQueryError = unknown


export function useGetApiProductIdStock<TData = Awaited<ReturnType<typeof getApiProductIdStock>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductIdStock>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductIdStock>>,
          TError,
          Awaited<ReturnType<typeof getApiProductIdStock>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductIdStock<TData = Awaited<ReturnType<typeof getApiProductIdStock>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductIdStock>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductIdStock>>,
          TError,
          Awaited<ReturnType<typeof getApiProductIdStock>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductIdStock<TData = Awaited<ReturnType<typeof getApiProductIdStock>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductIdStock>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductIdStock<TData = Awaited<ReturnType<typeof getApiProductIdStock>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductIdStock>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductIdStockQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiProductIdView = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Product/${id}/view`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiProductIdViewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProductIdView>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiProductIdView>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiProductIdView'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProductIdView>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiProductIdView(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiProductIdViewMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProductIdView>>>
    
    export type PostApiProductIdViewMutationError = unknown

    export const usePostApiProductIdView = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProductIdView>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProductIdView>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiProductIdViewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiProductCategoryCategoryId = (
    categoryId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListProductsProductListDto>(
      {url: `/api/Product/category/${categoryId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiProductCategoryCategoryIdQueryKey = (categoryId?: string,) => {
    return [
    `/api/Product/category/${categoryId}`
    ] as const;
    }

    
export const getGetApiProductCategoryCategoryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError = unknown>(categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductCategoryCategoryIdQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>> = ({ signal }) => getApiProductCategoryCategoryId(categoryId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductCategoryCategoryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>>
export type GetApiProductCategoryCategoryIdQueryError = unknown


export function useGetApiProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductCategoryCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductCategoryCategoryIdQueryOptions(categoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiProductFavorites = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListProductsProductListDto>(
      {url: `/api/Product/favorites`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiProductFavoritesQueryKey = () => {
    return [
    `/api/Product/favorites`
    ] as const;
    }

    
export const getGetApiProductFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductFavorites>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductFavorites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductFavoritesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductFavorites>>> = ({ signal }) => getApiProductFavorites(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductFavorites>>>
export type GetApiProductFavoritesQueryError = unknown


export function useGetApiProductFavorites<TData = Awaited<ReturnType<typeof getApiProductFavorites>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiProductFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductFavorites<TData = Awaited<ReturnType<typeof getApiProductFavorites>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiProductFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductFavorites<TData = Awaited<ReturnType<typeof getApiProductFavorites>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductFavorites<TData = Awaited<ReturnType<typeof getApiProductFavorites>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductFavoritesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiProductSlugSlug = (
    slug: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/Product/slug/${slug}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiProductSlugSlugQueryKey = (slug?: string,) => {
    return [
    `/api/Product/slug/${slug}`
    ] as const;
    }

    
export const getGetApiProductSlugSlugQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductSlugSlugQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductSlugSlug>>> = ({ signal }) => getApiProductSlugSlug(slug, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductSlugSlugQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductSlugSlug>>>
export type GetApiProductSlugSlugQueryError = MicrosoftAspNetCoreMvcProblemDetails


export function useGetApiProductSlugSlug<TData = Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductSlugSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiProductSlugSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductSlugSlug<TData = Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductSlugSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiProductSlugSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductSlugSlug<TData = Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductSlugSlug<TData = Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductSlugSlug>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductSlugSlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiProductStoreStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListProductsProductListDto>(
      {url: `/api/Product/store/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiProductStoreStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/Product/store/${storeId}`
    ] as const;
    }

    
export const getGetApiProductStoreStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductStoreStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductStoreStoreId>>> = ({ signal }) => getApiProductStoreStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductStoreStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductStoreStoreId>>>
export type GetApiProductStoreStoreIdQueryError = unknown


export function useGetApiProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductStoreStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiV1Product = (
    productsProductCreateDto: ProductsProductCreateDto,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/v1/Product`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productsProductCreateDto, signal
    },
      );
    }
  


export const getPostApiV1ProductMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Product>>, TError,{data: ProductsProductCreateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Product>>, TError,{data: ProductsProductCreateDto}, TContext> => {

const mutationKey = ['postApiV1Product'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Product>>, {data: ProductsProductCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Product(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ProductMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Product>>>
    export type PostApiV1ProductMutationBody = ProductsProductCreateDto
    export type PostApiV1ProductMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePostApiV1Product = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Product>>, TError,{data: ProductsProductCreateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Product>>,
        TError,
        {data: ProductsProductCreateDto},
        TContext
      > => {

      const mutationOptions = getPostApiV1ProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1Product = (
    params?: GetApiV1ProductParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResultProductsProductListDto>(
      {url: `/api/v1/Product`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1ProductQueryKey = (params?: GetApiV1ProductParams,) => {
    return [
    `/api/v1/Product`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1ProductQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Product>>, TError = unknown>(params?: GetApiV1ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Product>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Product>>> = ({ signal }) => getApiV1Product(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Product>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Product>>>
export type GetApiV1ProductQueryError = unknown


export function useGetApiV1Product<TData = Awaited<ReturnType<typeof getApiV1Product>>, TError = unknown>(
 params: undefined |  GetApiV1ProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Product>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Product>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Product>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Product<TData = Awaited<ReturnType<typeof getApiV1Product>>, TError = unknown>(
 params?: GetApiV1ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Product>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Product>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Product>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Product<TData = Awaited<ReturnType<typeof getApiV1Product>>, TError = unknown>(
 params?: GetApiV1ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Product>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1Product<TData = Awaited<ReturnType<typeof getApiV1Product>>, TError = unknown>(
 params?: GetApiV1ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Product>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1ProductId = (
    id: string,
    productsProductUpdateDto: ProductsProductUpdateDto,
 ) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/v1/Product/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: productsProductUpdateDto
    },
      );
    }
  


export const getPutApiV1ProductIdMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ProductId>>, TError,{id: string;data: ProductsProductUpdateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1ProductId>>, TError,{id: string;data: ProductsProductUpdateDto}, TContext> => {

const mutationKey = ['putApiV1ProductId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1ProductId>>, {id: string;data: ProductsProductUpdateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1ProductId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1ProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1ProductId>>>
    export type PutApiV1ProductIdMutationBody = ProductsProductUpdateDto
    export type PutApiV1ProductIdMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePutApiV1ProductId = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ProductId>>, TError,{id: string;data: ProductsProductUpdateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1ProductId>>,
        TError,
        {id: string;data: ProductsProductUpdateDto},
        TContext
      > => {

      const mutationOptions = getPutApiV1ProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiV1ProductId = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Product/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1ProductIdMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ProductId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ProductId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1ProductId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ProductId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1ProductId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ProductId>>>
    
    export type DeleteApiV1ProductIdMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const useDeleteApiV1ProductId = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ProductId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ProductId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1ProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1ProductId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/v1/Product/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProductIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/Product/${id}`
    ] as const;
    }

    
export const getGetApiV1ProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductId>>> = ({ signal }) => getApiV1ProductId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductId>>>
export type GetApiV1ProductIdQueryError = MicrosoftAspNetCoreMvcProblemDetails


export function useGetApiV1ProductId<TData = Awaited<ReturnType<typeof getApiV1ProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductId<TData = Awaited<ReturnType<typeof getApiV1ProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductId<TData = Awaited<ReturnType<typeof getApiV1ProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1ProductId<TData = Awaited<ReturnType<typeof getApiV1ProductId>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiV1ProductIdActive = (
    id: string,
    boolean: boolean,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Product/${id}/active`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: boolean
    },
      );
    }
  


export const getPatchApiV1ProductIdActiveMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdActive>>, TError,{id: string;data: boolean}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdActive>>, TError,{id: string;data: boolean}, TContext> => {

const mutationKey = ['patchApiV1ProductIdActive'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ProductIdActive>>, {id: string;data: boolean}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1ProductIdActive(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ProductIdActiveMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ProductIdActive>>>
    export type PatchApiV1ProductIdActiveMutationBody = boolean
    export type PatchApiV1ProductIdActiveMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePatchApiV1ProductIdActive = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdActive>>, TError,{id: string;data: boolean}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ProductIdActive>>,
        TError,
        {id: string;data: boolean},
        TContext
      > => {

      const mutationOptions = getPatchApiV1ProductIdActiveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiV1ProductIdFavorite = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Product/${id}/favorite`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiV1ProductIdFavoriteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ProductIdFavorite>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ProductIdFavorite>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiV1ProductIdFavorite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ProductIdFavorite>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiV1ProductIdFavorite(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ProductIdFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ProductIdFavorite>>>
    
    export type PostApiV1ProductIdFavoriteMutationError = unknown

    export const usePostApiV1ProductIdFavorite = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ProductIdFavorite>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ProductIdFavorite>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiV1ProductIdFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchApiV1ProductIdFeatured = (
    id: string,
    boolean: boolean,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Product/${id}/featured`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: boolean
    },
      );
    }
  


export const getPatchApiV1ProductIdFeaturedMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdFeatured>>, TError,{id: string;data: boolean}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdFeatured>>, TError,{id: string;data: boolean}, TContext> => {

const mutationKey = ['patchApiV1ProductIdFeatured'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ProductIdFeatured>>, {id: string;data: boolean}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1ProductIdFeatured(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ProductIdFeaturedMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ProductIdFeatured>>>
    export type PatchApiV1ProductIdFeaturedMutationBody = boolean
    export type PatchApiV1ProductIdFeaturedMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePatchApiV1ProductIdFeatured = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdFeatured>>, TError,{id: string;data: boolean}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ProductIdFeatured>>,
        TError,
        {id: string;data: boolean},
        TContext
      > => {

      const mutationOptions = getPatchApiV1ProductIdFeaturedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchApiV1ProductIdStock = (
    id: string,
    patchApiV1ProductIdStockBody: number,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Product/${id}/stock`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiV1ProductIdStockBody
    },
      );
    }
  


export const getPatchApiV1ProductIdStockMutationOptions = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdStock>>, TError,{id: string;data: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdStock>>, TError,{id: string;data: number}, TContext> => {

const mutationKey = ['patchApiV1ProductIdStock'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ProductIdStock>>, {id: string;data: number}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1ProductIdStock(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ProductIdStockMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ProductIdStock>>>
    export type PatchApiV1ProductIdStockMutationBody = number
    export type PatchApiV1ProductIdStockMutationError = MicrosoftAspNetCoreMvcProblemDetails

    export const usePatchApiV1ProductIdStock = <TError = MicrosoftAspNetCoreMvcProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ProductIdStock>>, TError,{id: string;data: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ProductIdStock>>,
        TError,
        {id: string;data: number},
        TContext
      > => {

      const mutationOptions = getPatchApiV1ProductIdStockMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1ProductIdStock = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseInt32>(
      {url: `/api/v1/Product/${id}/stock`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProductIdStockQueryKey = (id?: string,) => {
    return [
    `/api/v1/Product/${id}/stock`
    ] as const;
    }

    
export const getGetApiV1ProductIdStockQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductIdStockQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductIdStock>>> = ({ signal }) => getApiV1ProductIdStock(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductIdStockQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductIdStock>>>
export type GetApiV1ProductIdStockQueryError = unknown


export function useGetApiV1ProductIdStock<TData = Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductIdStock>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductIdStock>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductIdStock<TData = Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductIdStock>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductIdStock>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductIdStock<TData = Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1ProductIdStock<TData = Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductIdStock>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductIdStockQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiV1ProductIdView = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Product/${id}/view`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiV1ProductIdViewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ProductIdView>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ProductIdView>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiV1ProductIdView'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ProductIdView>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiV1ProductIdView(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ProductIdViewMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ProductIdView>>>
    
    export type PostApiV1ProductIdViewMutationError = unknown

    export const usePostApiV1ProductIdView = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ProductIdView>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ProductIdView>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiV1ProductIdViewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1ProductCategoryCategoryId = (
    categoryId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListProductsProductListDto>(
      {url: `/api/v1/Product/category/${categoryId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProductCategoryCategoryIdQueryKey = (categoryId?: string,) => {
    return [
    `/api/v1/Product/category/${categoryId}`
    ] as const;
    }

    
export const getGetApiV1ProductCategoryCategoryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError = unknown>(categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductCategoryCategoryIdQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>> = ({ signal }) => getApiV1ProductCategoryCategoryId(categoryId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductCategoryCategoryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>>
export type GetApiV1ProductCategoryCategoryIdQueryError = unknown


export function useGetApiV1ProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1ProductCategoryCategoryId<TData = Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError = unknown>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductCategoryCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductCategoryCategoryIdQueryOptions(categoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1ProductFavorites = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListProductsProductListDto>(
      {url: `/api/v1/Product/favorites`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProductFavoritesQueryKey = () => {
    return [
    `/api/v1/Product/favorites`
    ] as const;
    }

    
export const getGetApiV1ProductFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductFavoritesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductFavorites>>> = ({ signal }) => getApiV1ProductFavorites(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductFavorites>>>
export type GetApiV1ProductFavoritesQueryError = unknown


export function useGetApiV1ProductFavorites<TData = Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductFavorites<TData = Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductFavorites<TData = Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1ProductFavorites<TData = Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductFavoritesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1ProductSlugSlug = (
    slug: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseProductsProductDetailDto>(
      {url: `/api/v1/Product/slug/${slug}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProductSlugSlugQueryKey = (slug?: string,) => {
    return [
    `/api/v1/Product/slug/${slug}`
    ] as const;
    }

    
export const getGetApiV1ProductSlugSlugQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductSlugSlugQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>> = ({ signal }) => getApiV1ProductSlugSlug(slug, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductSlugSlugQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>>
export type GetApiV1ProductSlugSlugQueryError = MicrosoftAspNetCoreMvcProblemDetails


export function useGetApiV1ProductSlugSlug<TData = Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductSlugSlug<TData = Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductSlugSlug<TData = Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1ProductSlugSlug<TData = Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError = MicrosoftAspNetCoreMvcProblemDetails>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductSlugSlug>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductSlugSlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1ProductStoreStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListProductsProductListDto>(
      {url: `/api/v1/Product/store/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProductStoreStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/v1/Product/store/${storeId}`
    ] as const;
    }

    
export const getGetApiV1ProductStoreStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductStoreStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>> = ({ signal }) => getApiV1ProductStoreStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProductStoreStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>>
export type GetApiV1ProductStoreStoreIdQueryError = unknown


export function useGetApiV1ProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1ProductStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProductStoreStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




