/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import type { EntitiesHRMEmployeeStatus } from './entitiesHRMEmployeeStatus';

export interface HRMUpdateEmployeeRequest {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  department?: string | null;
  /** @nullable */
  hireDate?: string | null;
  /** @nullable */
  salary?: number | null;
  status?: EntitiesHRMEmployeeStatus;
  /** @nullable */
  managerId?: string | null;
  /** @nullable */
  storeId?: string | null;
  /** @nullable */
  skills?: string | null;
}
