/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import type { EnumsOrdersShippingMethodEnum } from './enumsOrdersShippingMethodEnum';

export interface OrderShippingInputDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  recipientName: string;
  /**
   * @minLength 1
   * @pattern ^[0-9]{10,11}$
   */
  phoneNumber: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  address: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  ward: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  district: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  city: string;
  /**
   * @maxLength 20
   * @nullable
   */
  postalCode?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  deliveryNote?: string | null;
  shippingMethod: EnumsOrdersShippingMethodEnum;
}
