/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import type { EnumsOrdersOrderStatus } from './enumsOrdersOrderStatus';
import type { OrdersOrderItemDTO } from './ordersOrderItemDTO';
import type { OrdersOrderShippingDto } from './ordersOrderShippingDto';

export interface OrdersCheckoutResponseDto {
  orderId?: string;
  /** @nullable */
  orderNumber?: string | null;
  status?: EnumsOrdersOrderStatus;
  /** @nullable */
  readonly statusText?: string | null;
  totalAmount?: number;
  createdAt?: string;
  storeId?: string;
  /** @nullable */
  storeName?: string | null;
  customerId?: string;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  items?: OrdersOrderItemDTO[] | null;
  shipping?: OrdersOrderShippingDto;
  /** @nullable */
  paymentUrl?: string | null;
  /** @nullable */
  paymentMethodUsed?: string | null;
}
