/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddressCreateCustomerAddressRequest,
  AddressUpdateCustomerAddressRequest,
  ApiResponseAddressCustomerAddressDto,
  ApiResponseBoolean,
  ApiResponseCRMCRMInteractionDto,
  ApiResponseCustomersCustomerDetailDto,
  ApiResponseCustomersCustomerOrderSummaryDto,
  ApiResponseCustomersCustomerStatisticsDto,
  ApiResponseListAddressCustomerAddressDto,
  ApiResponseListCRMCRMInteractionListDto,
  ApiResponseListCustomersCustomerListDto,
  ApiResponseListCustomersLoyaltyHistoryDto,
  ApiResponsePaginatedResponseCRMCRMInteractionListDto,
  ApiResponsePaginatedResponseCustomersCustomerListDto,
  ApiResponsePaginatedResponseOrdersOrderDetailDto,
  CRMCreateInteractionRequest,
  CRMUpdateInteractionRequest,
  CustomersAddPointsRequest,
  CustomersCreateCustomerRequest,
  CustomersDeductPointsRequest,
  CustomersUpdateCustomerRequest,
  CustomersUpdateTierRequest,
  GetApiAdminCustomerIdInteractionsParams,
  GetApiAdminCustomerIdOrdersParams,
  GetApiAdminCustomerInteractionsUpcomingParams,
  GetApiAdminCustomerParams,
  GetApiAdminCustomerSearchParams
} from '.././schemas';

import { apiClient } from '../../../src/lib/api/orval-client';




export const getApiAdminCustomer = (
    params?: GetApiAdminCustomerParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseCustomersCustomerListDto>(
      {url: `/api/AdminCustomer`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiAdminCustomerQueryKey = (params?: GetApiAdminCustomerParams,) => {
    return [
    `/api/AdminCustomer`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminCustomerQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomer>>, TError = unknown>(params?: GetApiAdminCustomerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomer>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomer>>> = ({ signal }) => getApiAdminCustomer(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomer>>>
export type GetApiAdminCustomerQueryError = unknown


export function useGetApiAdminCustomer<TData = Awaited<ReturnType<typeof getApiAdminCustomer>>, TError = unknown>(
 params: undefined |  GetApiAdminCustomerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomer>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomer>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomer<TData = Awaited<ReturnType<typeof getApiAdminCustomer>>, TError = unknown>(
 params?: GetApiAdminCustomerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomer>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomer>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomer<TData = Awaited<ReturnType<typeof getApiAdminCustomer>>, TError = unknown>(
 params?: GetApiAdminCustomerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomer>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomer<TData = Awaited<ReturnType<typeof getApiAdminCustomer>>, TError = unknown>(
 params?: GetApiAdminCustomerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomer>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiAdminCustomer = (
    customersCreateCustomerRequest: CustomersCreateCustomerRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/AdminCustomer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customersCreateCustomerRequest, signal
    },
      );
    }
  


export const getPostApiAdminCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomer>>, TError,{data: CustomersCreateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomer>>, TError,{data: CustomersCreateCustomerRequest}, TContext> => {

const mutationKey = ['postApiAdminCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminCustomer>>, {data: CustomersCreateCustomerRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAdminCustomer(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminCustomer>>>
    export type PostApiAdminCustomerMutationBody = CustomersCreateCustomerRequest
    export type PostApiAdminCustomerMutationError = unknown

    export const usePostApiAdminCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomer>>, TError,{data: CustomersCreateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminCustomer>>,
        TError,
        {data: CustomersCreateCustomerRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAdminCustomerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/AdminCustomer/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdQueryKey = (id?: string,) => {
    return [
    `/api/AdminCustomer/${id}`
    ] as const;
    }

    
export const getGetApiAdminCustomerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerId>>> = ({ signal }) => getApiAdminCustomerId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerId>>>
export type GetApiAdminCustomerIdQueryError = unknown


export function useGetApiAdminCustomerId<TData = Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerId<TData = Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerId<TData = Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerId<TData = Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiAdminCustomerId = (
    id: string,
    customersUpdateCustomerRequest: CustomersUpdateCustomerRequest,
 ) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/AdminCustomer/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: customersUpdateCustomerRequest
    },
      );
    }
  


export const getPutApiAdminCustomerIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerId>>, TError,{id: string;data: CustomersUpdateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerId>>, TError,{id: string;data: CustomersUpdateCustomerRequest}, TContext> => {

const mutationKey = ['putApiAdminCustomerId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminCustomerId>>, {id: string;data: CustomersUpdateCustomerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiAdminCustomerId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminCustomerIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminCustomerId>>>
    export type PutApiAdminCustomerIdMutationBody = CustomersUpdateCustomerRequest
    export type PutApiAdminCustomerIdMutationError = unknown

    export const usePutApiAdminCustomerId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerId>>, TError,{id: string;data: CustomersUpdateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminCustomerId>>,
        TError,
        {id: string;data: CustomersUpdateCustomerRequest},
        TContext
      > => {

      const mutationOptions = getPutApiAdminCustomerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiAdminCustomerId = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/AdminCustomer/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiAdminCustomerIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiAdminCustomerId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAdminCustomerId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiAdminCustomerId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAdminCustomerIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAdminCustomerId>>>
    
    export type DeleteApiAdminCustomerIdMutationError = unknown

    export const useDeleteApiAdminCustomerId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAdminCustomerId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiAdminCustomerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerIdAddresses = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListAddressCustomerAddressDto>(
      {url: `/api/AdminCustomer/${id}/addresses`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdAddressesQueryKey = (id?: string,) => {
    return [
    `/api/AdminCustomer/${id}/addresses`
    ] as const;
    }

    
export const getGetApiAdminCustomerIdAddressesQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdAddressesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>> = ({ signal }) => getApiAdminCustomerIdAddresses(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdAddressesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>>
export type GetApiAdminCustomerIdAddressesQueryError = unknown


export function useGetApiAdminCustomerIdAddresses<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdAddresses<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdAddresses<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerIdAddresses<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdAddresses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdAddressesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiAdminCustomerIdAddressesAddressIdDefault = (
    id: string,
    addressId: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/AdminCustomer/${id}/addresses/${addressId}/default`, method: 'PUT'
    },
      );
    }
  


export const getPutApiAdminCustomerIdAddressesAddressIdDefaultMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerIdAddressesAddressIdDefault>>, TError,{id: string;addressId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerIdAddressesAddressIdDefault>>, TError,{id: string;addressId: string}, TContext> => {

const mutationKey = ['putApiAdminCustomerIdAddressesAddressIdDefault'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminCustomerIdAddressesAddressIdDefault>>, {id: string;addressId: string}> = (props) => {
          const {id,addressId} = props ?? {};

          return  putApiAdminCustomerIdAddressesAddressIdDefault(id,addressId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminCustomerIdAddressesAddressIdDefaultMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminCustomerIdAddressesAddressIdDefault>>>
    
    export type PutApiAdminCustomerIdAddressesAddressIdDefaultMutationError = unknown

    export const usePutApiAdminCustomerIdAddressesAddressIdDefault = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerIdAddressesAddressIdDefault>>, TError,{id: string;addressId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminCustomerIdAddressesAddressIdDefault>>,
        TError,
        {id: string;addressId: string},
        TContext
      > => {

      const mutationOptions = getPutApiAdminCustomerIdAddressesAddressIdDefaultMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerIdInteractions = (
    id: string,
    params?: GetApiAdminCustomerIdInteractionsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseCRMCRMInteractionListDto>(
      {url: `/api/AdminCustomer/${id}/interactions`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdInteractionsQueryKey = (id?: string,
    params?: GetApiAdminCustomerIdInteractionsParams,) => {
    return [
    `/api/AdminCustomer/${id}/interactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminCustomerIdInteractionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError = unknown>(id: string,
    params?: GetApiAdminCustomerIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdInteractionsQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>> = ({ signal }) => getApiAdminCustomerIdInteractions(id,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdInteractionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>>
export type GetApiAdminCustomerIdInteractionsQueryError = unknown


export function useGetApiAdminCustomerIdInteractions<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError = unknown>(
 id: string,
    params: undefined |  GetApiAdminCustomerIdInteractionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdInteractions<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError = unknown>(
 id: string,
    params?: GetApiAdminCustomerIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdInteractions<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError = unknown>(
 id: string,
    params?: GetApiAdminCustomerIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerIdInteractions<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError = unknown>(
 id: string,
    params?: GetApiAdminCustomerIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdInteractions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdInteractionsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAdminCustomerIdLoyaltyHistory = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListCustomersLoyaltyHistoryDto>(
      {url: `/api/AdminCustomer/${id}/loyalty-history`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdLoyaltyHistoryQueryKey = (id?: string,) => {
    return [
    `/api/AdminCustomer/${id}/loyalty-history`
    ] as const;
    }

    
export const getGetApiAdminCustomerIdLoyaltyHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdLoyaltyHistoryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>> = ({ signal }) => getApiAdminCustomerIdLoyaltyHistory(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdLoyaltyHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>>
export type GetApiAdminCustomerIdLoyaltyHistoryQueryError = unknown


export function useGetApiAdminCustomerIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdLoyaltyHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdLoyaltyHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiAdminCustomerIdLoyaltyAdd = (
    id: string,
    customersAddPointsRequest: CustomersAddPointsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/AdminCustomer/${id}/loyalty/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customersAddPointsRequest, signal
    },
      );
    }
  


export const getPostApiAdminCustomerIdLoyaltyAddMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyAdd>>, TError,{id: string;data: CustomersAddPointsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyAdd>>, TError,{id: string;data: CustomersAddPointsRequest}, TContext> => {

const mutationKey = ['postApiAdminCustomerIdLoyaltyAdd'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyAdd>>, {id: string;data: CustomersAddPointsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAdminCustomerIdLoyaltyAdd(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminCustomerIdLoyaltyAddMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyAdd>>>
    export type PostApiAdminCustomerIdLoyaltyAddMutationBody = CustomersAddPointsRequest
    export type PostApiAdminCustomerIdLoyaltyAddMutationError = unknown

    export const usePostApiAdminCustomerIdLoyaltyAdd = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyAdd>>, TError,{id: string;data: CustomersAddPointsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyAdd>>,
        TError,
        {id: string;data: CustomersAddPointsRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAdminCustomerIdLoyaltyAddMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiAdminCustomerIdLoyaltyDeduct = (
    id: string,
    customersDeductPointsRequest: CustomersDeductPointsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/AdminCustomer/${id}/loyalty/deduct`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customersDeductPointsRequest, signal
    },
      );
    }
  


export const getPostApiAdminCustomerIdLoyaltyDeductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyDeduct>>, TError,{id: string;data: CustomersDeductPointsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyDeduct>>, TError,{id: string;data: CustomersDeductPointsRequest}, TContext> => {

const mutationKey = ['postApiAdminCustomerIdLoyaltyDeduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyDeduct>>, {id: string;data: CustomersDeductPointsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAdminCustomerIdLoyaltyDeduct(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminCustomerIdLoyaltyDeductMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyDeduct>>>
    export type PostApiAdminCustomerIdLoyaltyDeductMutationBody = CustomersDeductPointsRequest
    export type PostApiAdminCustomerIdLoyaltyDeductMutationError = unknown

    export const usePostApiAdminCustomerIdLoyaltyDeduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyDeduct>>, TError,{id: string;data: CustomersDeductPointsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminCustomerIdLoyaltyDeduct>>,
        TError,
        {id: string;data: CustomersDeductPointsRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAdminCustomerIdLoyaltyDeductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerIdOrders = (
    id: string,
    params?: GetApiAdminCustomerIdOrdersParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseOrdersOrderDetailDto>(
      {url: `/api/AdminCustomer/${id}/orders`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdOrdersQueryKey = (id?: string,
    params?: GetApiAdminCustomerIdOrdersParams,) => {
    return [
    `/api/AdminCustomer/${id}/orders`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminCustomerIdOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError = unknown>(id: string,
    params?: GetApiAdminCustomerIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdOrdersQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>> = ({ signal }) => getApiAdminCustomerIdOrders(id,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>>
export type GetApiAdminCustomerIdOrdersQueryError = unknown


export function useGetApiAdminCustomerIdOrders<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError = unknown>(
 id: string,
    params: undefined |  GetApiAdminCustomerIdOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdOrders<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError = unknown>(
 id: string,
    params?: GetApiAdminCustomerIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdOrders<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError = unknown>(
 id: string,
    params?: GetApiAdminCustomerIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerIdOrders<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError = unknown>(
 id: string,
    params?: GetApiAdminCustomerIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrders>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdOrdersQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAdminCustomerIdOrdersSummary = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerOrderSummaryDto>(
      {url: `/api/AdminCustomer/${id}/orders/summary`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdOrdersSummaryQueryKey = (id?: string,) => {
    return [
    `/api/AdminCustomer/${id}/orders/summary`
    ] as const;
    }

    
export const getGetApiAdminCustomerIdOrdersSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdOrdersSummaryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>> = ({ signal }) => getApiAdminCustomerIdOrdersSummary(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdOrdersSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>>
export type GetApiAdminCustomerIdOrdersSummaryQueryError = unknown


export function useGetApiAdminCustomerIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdOrdersSummary>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdOrdersSummaryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAdminCustomerIdStatistics = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerStatisticsDto>(
      {url: `/api/AdminCustomer/${id}/statistics`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerIdStatisticsQueryKey = (id?: string,) => {
    return [
    `/api/AdminCustomer/${id}/statistics`
    ] as const;
    }

    
export const getGetApiAdminCustomerIdStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerIdStatisticsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>> = ({ signal }) => getApiAdminCustomerIdStatistics(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerIdStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>>
export type GetApiAdminCustomerIdStatisticsQueryError = unknown


export function useGetApiAdminCustomerIdStatistics<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdStatistics<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerIdStatistics<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerIdStatistics<TData = Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerIdStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerIdStatisticsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiAdminCustomerIdTier = (
    id: string,
    customersUpdateTierRequest: CustomersUpdateTierRequest,
 ) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/AdminCustomer/${id}/tier`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: customersUpdateTierRequest
    },
      );
    }
  


export const getPutApiAdminCustomerIdTierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerIdTier>>, TError,{id: string;data: CustomersUpdateTierRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerIdTier>>, TError,{id: string;data: CustomersUpdateTierRequest}, TContext> => {

const mutationKey = ['putApiAdminCustomerIdTier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminCustomerIdTier>>, {id: string;data: CustomersUpdateTierRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiAdminCustomerIdTier(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminCustomerIdTierMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminCustomerIdTier>>>
    export type PutApiAdminCustomerIdTierMutationBody = CustomersUpdateTierRequest
    export type PutApiAdminCustomerIdTierMutationError = unknown

    export const usePutApiAdminCustomerIdTier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerIdTier>>, TError,{id: string;data: CustomersUpdateTierRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminCustomerIdTier>>,
        TError,
        {id: string;data: CustomersUpdateTierRequest},
        TContext
      > => {

      const mutationOptions = getPutApiAdminCustomerIdTierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiAdminCustomerAddresses = (
    addressCreateCustomerAddressRequest: AddressCreateCustomerAddressRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseAddressCustomerAddressDto>(
      {url: `/api/AdminCustomer/addresses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addressCreateCustomerAddressRequest, signal
    },
      );
    }
  


export const getPostApiAdminCustomerAddressesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerAddresses>>, TError,{data: AddressCreateCustomerAddressRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerAddresses>>, TError,{data: AddressCreateCustomerAddressRequest}, TContext> => {

const mutationKey = ['postApiAdminCustomerAddresses'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminCustomerAddresses>>, {data: AddressCreateCustomerAddressRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAdminCustomerAddresses(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminCustomerAddressesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminCustomerAddresses>>>
    export type PostApiAdminCustomerAddressesMutationBody = AddressCreateCustomerAddressRequest
    export type PostApiAdminCustomerAddressesMutationError = unknown

    export const usePostApiAdminCustomerAddresses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerAddresses>>, TError,{data: AddressCreateCustomerAddressRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminCustomerAddresses>>,
        TError,
        {data: AddressCreateCustomerAddressRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAdminCustomerAddressesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerAddressesAddressId = (
    addressId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseAddressCustomerAddressDto>(
      {url: `/api/AdminCustomer/addresses/${addressId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerAddressesAddressIdQueryKey = (addressId?: string,) => {
    return [
    `/api/AdminCustomer/addresses/${addressId}`
    ] as const;
    }

    
export const getGetApiAdminCustomerAddressesAddressIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError = unknown>(addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerAddressesAddressIdQueryKey(addressId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>> = ({ signal }) => getApiAdminCustomerAddressesAddressId(addressId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(addressId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerAddressesAddressIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>>
export type GetApiAdminCustomerAddressesAddressIdQueryError = unknown


export function useGetApiAdminCustomerAddressesAddressId<TData = Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError = unknown>(
 addressId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerAddressesAddressId<TData = Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError = unknown>(
 addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerAddressesAddressId<TData = Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError = unknown>(
 addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerAddressesAddressId<TData = Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError = unknown>(
 addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerAddressesAddressId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerAddressesAddressIdQueryOptions(addressId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiAdminCustomerAddressesAddressId = (
    addressId: string,
    addressUpdateCustomerAddressRequest: AddressUpdateCustomerAddressRequest,
 ) => {
      
      
      return apiClient<ApiResponseAddressCustomerAddressDto>(
      {url: `/api/AdminCustomer/addresses/${addressId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addressUpdateCustomerAddressRequest
    },
      );
    }
  


export const getPutApiAdminCustomerAddressesAddressIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerAddressesAddressId>>, TError,{addressId: string;data: AddressUpdateCustomerAddressRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerAddressesAddressId>>, TError,{addressId: string;data: AddressUpdateCustomerAddressRequest}, TContext> => {

const mutationKey = ['putApiAdminCustomerAddressesAddressId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminCustomerAddressesAddressId>>, {addressId: string;data: AddressUpdateCustomerAddressRequest}> = (props) => {
          const {addressId,data} = props ?? {};

          return  putApiAdminCustomerAddressesAddressId(addressId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminCustomerAddressesAddressIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminCustomerAddressesAddressId>>>
    export type PutApiAdminCustomerAddressesAddressIdMutationBody = AddressUpdateCustomerAddressRequest
    export type PutApiAdminCustomerAddressesAddressIdMutationError = unknown

    export const usePutApiAdminCustomerAddressesAddressId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerAddressesAddressId>>, TError,{addressId: string;data: AddressUpdateCustomerAddressRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminCustomerAddressesAddressId>>,
        TError,
        {addressId: string;data: AddressUpdateCustomerAddressRequest},
        TContext
      > => {

      const mutationOptions = getPutApiAdminCustomerAddressesAddressIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiAdminCustomerAddressesAddressId = (
    addressId: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/AdminCustomer/addresses/${addressId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiAdminCustomerAddressesAddressIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerAddressesAddressId>>, TError,{addressId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerAddressesAddressId>>, TError,{addressId: string}, TContext> => {

const mutationKey = ['deleteApiAdminCustomerAddressesAddressId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAdminCustomerAddressesAddressId>>, {addressId: string}> = (props) => {
          const {addressId} = props ?? {};

          return  deleteApiAdminCustomerAddressesAddressId(addressId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAdminCustomerAddressesAddressIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAdminCustomerAddressesAddressId>>>
    
    export type DeleteApiAdminCustomerAddressesAddressIdMutationError = unknown

    export const useDeleteApiAdminCustomerAddressesAddressId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerAddressesAddressId>>, TError,{addressId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAdminCustomerAddressesAddressId>>,
        TError,
        {addressId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiAdminCustomerAddressesAddressIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiAdminCustomerInteractions = (
    cRMCreateInteractionRequest: CRMCreateInteractionRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/AdminCustomer/interactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cRMCreateInteractionRequest, signal
    },
      );
    }
  


export const getPostApiAdminCustomerInteractionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerInteractions>>, TError,{data: CRMCreateInteractionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerInteractions>>, TError,{data: CRMCreateInteractionRequest}, TContext> => {

const mutationKey = ['postApiAdminCustomerInteractions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminCustomerInteractions>>, {data: CRMCreateInteractionRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAdminCustomerInteractions(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminCustomerInteractionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminCustomerInteractions>>>
    export type PostApiAdminCustomerInteractionsMutationBody = CRMCreateInteractionRequest
    export type PostApiAdminCustomerInteractionsMutationError = unknown

    export const usePostApiAdminCustomerInteractions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminCustomerInteractions>>, TError,{data: CRMCreateInteractionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminCustomerInteractions>>,
        TError,
        {data: CRMCreateInteractionRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAdminCustomerInteractionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerInteractionsInteractionId = (
    interactionId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/AdminCustomer/interactions/${interactionId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiAdminCustomerInteractionsInteractionIdQueryKey = (interactionId?: string,) => {
    return [
    `/api/AdminCustomer/interactions/${interactionId}`
    ] as const;
    }

    
export const getGetApiAdminCustomerInteractionsInteractionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError = unknown>(interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerInteractionsInteractionIdQueryKey(interactionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>> = ({ signal }) => getApiAdminCustomerInteractionsInteractionId(interactionId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(interactionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerInteractionsInteractionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>>
export type GetApiAdminCustomerInteractionsInteractionIdQueryError = unknown


export function useGetApiAdminCustomerInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsInteractionId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerInteractionsInteractionIdQueryOptions(interactionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiAdminCustomerInteractionsInteractionId = (
    interactionId: string,
    cRMUpdateInteractionRequest: CRMUpdateInteractionRequest,
 ) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/AdminCustomer/interactions/${interactionId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: cRMUpdateInteractionRequest
    },
      );
    }
  


export const getPutApiAdminCustomerInteractionsInteractionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionId>>, TError,{interactionId: string;data: CRMUpdateInteractionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionId>>, TError,{interactionId: string;data: CRMUpdateInteractionRequest}, TContext> => {

const mutationKey = ['putApiAdminCustomerInteractionsInteractionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionId>>, {interactionId: string;data: CRMUpdateInteractionRequest}> = (props) => {
          const {interactionId,data} = props ?? {};

          return  putApiAdminCustomerInteractionsInteractionId(interactionId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminCustomerInteractionsInteractionIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionId>>>
    export type PutApiAdminCustomerInteractionsInteractionIdMutationBody = CRMUpdateInteractionRequest
    export type PutApiAdminCustomerInteractionsInteractionIdMutationError = unknown

    export const usePutApiAdminCustomerInteractionsInteractionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionId>>, TError,{interactionId: string;data: CRMUpdateInteractionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionId>>,
        TError,
        {interactionId: string;data: CRMUpdateInteractionRequest},
        TContext
      > => {

      const mutationOptions = getPutApiAdminCustomerInteractionsInteractionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiAdminCustomerInteractionsInteractionId = (
    interactionId: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/AdminCustomer/interactions/${interactionId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiAdminCustomerInteractionsInteractionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerInteractionsInteractionId>>, TError,{interactionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerInteractionsInteractionId>>, TError,{interactionId: string}, TContext> => {

const mutationKey = ['deleteApiAdminCustomerInteractionsInteractionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAdminCustomerInteractionsInteractionId>>, {interactionId: string}> = (props) => {
          const {interactionId} = props ?? {};

          return  deleteApiAdminCustomerInteractionsInteractionId(interactionId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAdminCustomerInteractionsInteractionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAdminCustomerInteractionsInteractionId>>>
    
    export type DeleteApiAdminCustomerInteractionsInteractionIdMutationError = unknown

    export const useDeleteApiAdminCustomerInteractionsInteractionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminCustomerInteractionsInteractionId>>, TError,{interactionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAdminCustomerInteractionsInteractionId>>,
        TError,
        {interactionId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiAdminCustomerInteractionsInteractionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const putApiAdminCustomerInteractionsInteractionIdComplete = (
    interactionId: string,
 ) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/AdminCustomer/interactions/${interactionId}/complete`, method: 'PUT'
    },
      );
    }
  


export const getPutApiAdminCustomerInteractionsInteractionIdCompleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionIdComplete>>, TError,{interactionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionIdComplete>>, TError,{interactionId: string}, TContext> => {

const mutationKey = ['putApiAdminCustomerInteractionsInteractionIdComplete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionIdComplete>>, {interactionId: string}> = (props) => {
          const {interactionId} = props ?? {};

          return  putApiAdminCustomerInteractionsInteractionIdComplete(interactionId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminCustomerInteractionsInteractionIdCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionIdComplete>>>
    
    export type PutApiAdminCustomerInteractionsInteractionIdCompleteMutationError = unknown

    export const usePutApiAdminCustomerInteractionsInteractionIdComplete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionIdComplete>>, TError,{interactionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminCustomerInteractionsInteractionIdComplete>>,
        TError,
        {interactionId: string},
        TContext
      > => {

      const mutationOptions = getPutApiAdminCustomerInteractionsInteractionIdCompleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiAdminCustomerInteractionsUpcoming = (
    params?: GetApiAdminCustomerInteractionsUpcomingParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListCRMCRMInteractionListDto>(
      {url: `/api/AdminCustomer/interactions/upcoming`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiAdminCustomerInteractionsUpcomingQueryKey = (params?: GetApiAdminCustomerInteractionsUpcomingParams,) => {
    return [
    `/api/AdminCustomer/interactions/upcoming`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminCustomerInteractionsUpcomingQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError = unknown>(params?: GetApiAdminCustomerInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerInteractionsUpcomingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>> = ({ signal }) => getApiAdminCustomerInteractionsUpcoming(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerInteractionsUpcomingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>>
export type GetApiAdminCustomerInteractionsUpcomingQueryError = unknown


export function useGetApiAdminCustomerInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError = unknown>(
 params: undefined |  GetApiAdminCustomerInteractionsUpcomingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError = unknown>(
 params?: GetApiAdminCustomerInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError = unknown>(
 params?: GetApiAdminCustomerInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError = unknown>(
 params?: GetApiAdminCustomerInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerInteractionsUpcoming>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerInteractionsUpcomingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiAdminCustomerSearch = (
    params?: GetApiAdminCustomerSearchParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListCustomersCustomerListDto>(
      {url: `/api/AdminCustomer/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiAdminCustomerSearchQueryKey = (params?: GetApiAdminCustomerSearchParams,) => {
    return [
    `/api/AdminCustomer/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminCustomerSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError = unknown>(params?: GetApiAdminCustomerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminCustomerSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>> = ({ signal }) => getApiAdminCustomerSearch(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminCustomerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>>
export type GetApiAdminCustomerSearchQueryError = unknown


export function useGetApiAdminCustomerSearch<TData = Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError = unknown>(
 params: undefined |  GetApiAdminCustomerSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerSearch<TData = Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError = unknown>(
 params?: GetApiAdminCustomerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminCustomerSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminCustomerSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminCustomerSearch<TData = Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError = unknown>(
 params?: GetApiAdminCustomerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminCustomerSearch<TData = Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError = unknown>(
 params?: GetApiAdminCustomerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminCustomerSearch>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminCustomerSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




