/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { ActionTypeDtoMetadata } from './actionTypeDtoMetadata';

/**
 * DTO for action type definitions used in ritual pattern matching
 */
export interface ActionTypeDto {
  /**
   * Type of action (e.g., "ViewProduct", "AddToCart", "BrowseCategory")
   * @nullable
   */
  type?: string | null;
  /**
   * Optional product category ID associated with the action
   * @nullable
   */
  productCategoryId?: string | null;
  /**
   * Additional metadata for the action type
   * @nullable
   */
  metadata?: ActionTypeDtoMetadata;
}
