/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export type AddressType = typeof AddressType[keyof typeof AddressType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressType = {
  home: 'home',
  office: 'office',
  other: 'other',
} as const;
