/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { AddressResponseDto } from './addressResponseDto';

export interface AddressResponseDtoListApiResponse {
  success?: boolean;
  /** @nullable */
  data?: AddressResponseDto[] | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
