/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { ActionDto } from './actionDto';
import type { CartItemDto } from './cartItemDto';

/**
 * Request model for analyzing action sequences
 */
export interface AnalyzeRecommendationRequest {
  /**
   * Sequence of user actions to analyze
   * @nullable
   */
  actionSequence?: ActionDto[] | null;
  /**
   * Items currently in the user's cart
   * @nullable
   */
  cartItems?: CartItemDto[] | null;
}
