/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';

/**
 * Request to bulk update order statuses
 */
export interface BulkUpdateStatusRequest {
  /**
   * List of order IDs to update
   * @nullable
   */
  orderIds?: string[] | null;
  newStatus?: OrderStatus;
  /**
   * Optional reason for the update
   * @nullable
   */
  reason?: string | null;
}
