/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CategoryDto } from './categoryDto';

export interface CategoryDtoIEnumerableApiResponse {
  success?: boolean;
  /** @nullable */
  data?: CategoryDto[] | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
