/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { CategoryDetailDto } from './categoryDetailDto';

export interface CategoryDetailDtoApiResponse {
  success?: boolean;
  data?: CategoryDetailDto;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
