/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CategoryDto } from './categoryDto';
import type { ProductSummaryDto } from './productSummaryDto';

export interface CategoryDetailDto {
  id?: string;
  storeId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  parentName?: string | null;
  isActive?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  subCategoriesCount?: number;
  productsCount?: number;
  /** @nullable */
  subCategories?: CategoryDto[] | null;
  /** @nullable */
  products?: ProductSummaryDto[] | null;
}
