/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { AddressType } from './addressType';

export interface CreateAddressDto {
  /**
   * @minLength 1
   * @maxLength 500
   */
  streetAddress: string;
  /**
   * @maxLength 200
   * @nullable
   */
  city?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  postalCode?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  state?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  country?: string | null;
  addressType: AddressType;
  /**
   * @maxLength 200
   * @nullable
   */
  recipientName?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  phoneNumber?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  email?: string | null;
  isDefault?: boolean;
  isPrimary?: boolean;
}
