/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CRMInteractionListDto } from './cRMInteractionListDto';

export interface CRMInteractionListDtoPaginatedResponse {
  /** @nullable */
  items?: CRMInteractionListDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalItems?: number;
  readonly totalPages?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
