/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CustomerDetailDto } from './customerDetailDto';
import type { UserDetailDTO } from './userDetailDTO';

/**
 * DTO for combined Customer + User information
Used in GET /api/v1/AdminCustomer/{id} endpoint
 */
export interface CustomerWithUserDto {
  customer?: CustomerDetailDto;
  user?: UserDetailDTO;
}
