/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * DTO representing a customizable option within a package product.
Customizable options allow customers to modify quantities of specific items in a package.
 */
export interface CustomizableOptionDto {
  /**
   * Unique identifier for the customizable option (e.g., "opt-xoi", "opt-che").
   * @minLength 0
   * @maxLength 100
   */
  id: string;
  /**
   * Display name of the customizable option (e.g., "Xôi gấc đậu xanh", "Chè trôi nước").
   * @minLength 0
   * @maxLength 200
   */
  name: string;
  /**
   * Default quantity included in the package for this option.
   * @minimum 1
   * @maximum 2147483647
   */
  baseQuantity: number;
  /**
   * Price per unit of this option (e.g., 45,000đ per dĩa of xôi).
   * @minimum 0
   */
  unitPrice: number;
  /**
   * Minimum quantity a customer can order for this option.
   * @minimum 1
   * @maximum 2147483647
   */
  minQuantity: number;
  /**
   * Maximum quantity a customer can order for this option. Null means unlimited.
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  maxQuantity?: number | null;
  /**
   * Unit of measurement for this option (e.g., "dĩa", "chén", "bộ").
   * @minLength 0
   * @maxLength 50
   */
  unit: string;
}
