/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { CustomerAddressDto } from './customerAddressDto';

export interface CustomerAddressDtoApiResponse {
  success?: boolean;
  data?: CustomerAddressDto;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
