/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CustomerListDtoPaginatedResponse } from './customerListDtoPaginatedResponse';

export interface CustomerListDtoPaginatedResponseApiResponse {
  success?: boolean;
  data?: CustomerListDtoPaginatedResponse;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
