/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export interface CustomerOrderSummaryDto {
  customerId?: string;
  totalOrders?: number;
  completedOrders?: number;
  pendingOrders?: number;
  cancelledOrders?: number;
  totalSpent?: number;
  averageOrderValue?: number;
  /** @nullable */
  firstOrderDate?: string | null;
  /** @nullable */
  lastOrderDate?: string | null;
}
