/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export interface CustomerStatisticsDto {
  customerId?: string;
  totalOrders?: number;
  totalSpent?: number;
  averageOrderValue?: number;
  totalInteractions?: number;
  /** @nullable */
  lastOrderDate?: string | null;
  /** @nullable */
  lastInteractionDate?: string | null;
  loyaltyPoints?: number;
  /** @nullable */
  tier?: string | null;
}
