/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { AddressType } from './addressType';

/**
 * DTO for customer address details
 */
export interface CustomerAddressDto {
  id?: string;
  customerId?: string;
  /** @nullable */
  streetAddress?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  country?: string | null;
  addressType?: AddressType;
  /** @nullable */
  addressTypeText?: string | null;
  /** @nullable */
  recipientName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  email?: string | null;
  isDefault?: boolean;
  isPrimary?: boolean;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
