/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export interface CustomerDto {
  customerId?: string;
  /** @nullable */
  customerAvatar?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
  loyaltyPoints?: number;
  /** @nullable */
  tier?: string | null;
  /** @nullable */
  email?: string | null;
  isActive?: boolean;
}
