/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export interface CustomerListDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  loyaltyPoints?: number;
  /** @nullable */
  tier?: string | null;
  isActive?: boolean;
  createdAt?: string;
  totalOrders?: number;
  totalSpent?: number;
}
