/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * Request model for disabling a ritual
 */
export interface DisableRitualRequest {
  /** The ID of the ritual to disable */
  ritualId?: string;
}
