/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * Request model for dismissing a ritual recommendation
 */
export interface DismissRitualRequest {
  /** The ID of the ritual to dismiss */
  ritualId?: string;
  /**
   * Optional reason for dismissal
   * @nullable
   */
  reason?: string | null;
}
