/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * Field-level validation errors
Key: field name, Value: array of error messages for that field
 * @nullable
 */
export type ErrorResponseErrors = {[key: string]: string[]} | null;
