/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { ErrorResponseErrors } from './errorResponseErrors';

/**
 * Standardized error response format with error codes for programmatic handling
Requirements: 8.1, 8.2, 8.3, 8.4, 8.5
 */
export interface ErrorResponse {
  /** Indicates if the request was successful */
  success?: boolean;
  /**
   * Human-readable error message
   * @nullable
   */
  message?: string | null;
  /**
   * Machine-readable error code for programmatic handling
Examples: INVALID_DATE_RANGE, NEGATIVE_BUDGET, CAMPAIGN_NOT_DRAFT, etc.
   * @nullable
   */
  errorCode?: string | null;
  /**
   * Field-level validation errors
Key: field name, Value: array of error messages for that field
   * @nullable
   */
  errors?: ErrorResponseErrors;
  /** HTTP status code */
  statusCode?: number;
  /** Timestamp when the error occurred */
  timestamp?: string;
}
