/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { ItemExplanationDto } from './itemExplanationDto';

/**
 * DTO for FE-AI explanation output generated by Gemini API
 */
export interface ExplanationPayloadDto {
  /**
   * Name of the ritual being explained
   * @nullable
   */
  ritualName?: string | null;
  /**
   * Cultural context and significance of the ritual
   * @nullable
   */
  culturalContext?: string | null;
  /**
   * Explanations for each recommended item
   * @nullable
   */
  itemExplanations?: ItemExplanationDto[] | null;
  /**
   * Sources or references supporting the explanation
   * @nullable
   */
  sources?: string[] | null;
  /**
   * Indicates whether explanation was generated by Gemini or fallback template
   * @nullable
   */
  generatedBy?: string | null;
}
