/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { RecommendationPayloadDto } from './recommendationPayloadDto';

/**
 * Request model for generating explanations
 */
export interface GenerateExplanationRequest {
  recommendationPayload?: RecommendationPayloadDto;
}
