/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';

export type GetApiV1OrderParams = {
/**
 * @minimum 1
 * @maximum 2147483647
 */
Page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
PageSize?: number;
/**
 * @maxLength 100
 */
Keyword?: string;
CustomerId?: string;
StoreId?: string;
Status?: OrderStatus;
FromDate?: string;
ToDate?: string;
/**
 * @minimum 0
 */
MinAmount?: number;
/**
 * @minimum 0
 */
MaxAmount?: number;
/**
 * @maxLength 50
 */
SortBy?: string;
SortDescending?: boolean;
};
