/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';

export type GetApiV1CheckoutMyOrdersParams = {
/**
 * @minimum 1
 * @maximum 2147483647
 */
Page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
PageSize?: number;
/**
 * Search by OrderNumber or CustomerName (partial match, case-insensitive)
 * @maxLength 100
 */
Keyword?: string;
/**
 * Filter by specific customer
 */
CustomerId?: string;
/**
 * Filter by specific store
 */
StoreId?: string;
/**
 * Filter by order status (enum)
Example: 1 (Pending), 2 (Confirmed), etc.
 */
Status?: OrderStatus;
/**
 * Filter orders created on or after this date
 */
FromDate?: string;
/**
 * Filter orders created on or before this date
 */
ToDate?: string;
/**
 * Filter by minimum order amount
 * @minimum 0
 */
MinAmount?: number;
/**
 * Filter by maximum order amount
 * @minimum 0
 */
MaxAmount?: number;
/**
 * Sort by field: "CreatedAt", "TotalAmount", "OrderNumber", "Status", "CustomerName"
 * @maxLength 50
 */
SortBy?: string;
/**
 * Sort descending (true) or ascending (false)
 */
SortDescending?: boolean;
/**
 * Filter by type: "product" or "service"
If null, returns all types (backward compatible)
 * @maxLength 50
 */
Type?: string;
/**
 * Filter by service category (only applies when type='service')
Values: ancestor-worship, opening-ceremony, wedding, buddha-worship, new-house, feng-shui-consultation
 * @maxLength 100
 */
ServiceCategory?: string;
};
