/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { CRMInteractionType } from './cRMInteractionType';
import type { CRMInteractionStatus } from './cRMInteractionStatus';

export type GetApiV1CustomerAdminIdInteractionsParams = {
/**
 * @minimum 1
 * @maximum 2147483647
 */
Page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
PageSize?: number;
/**
 * @maxLength 50
 */
SortBy?: string;
SortDescending?: boolean;
Skip?: number;
CustomerId?: string;
Type?: CRMInteractionType;
Status?: CRMInteractionStatus;
/**
 * @maxLength 100
 */
SearchTerm?: string;
FromDate?: string;
ToDate?: string;
FollowUpFromDate?: string;
FollowUpToDate?: string;
CreatedBy?: string;
HasPendingFollowUp?: boolean;
};
