/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

export type GetApiV1ProductParams = {
Page?: number;
PageSize?: number;
SearchTerm?: string;
CategoryId?: string;
StoreId?: string;
IsActive?: boolean;
IsFeatured?: boolean;
MinPrice?: number;
MaxPrice?: number;
SortBy?: string;
IsDescending?: boolean;
/**
 * Filter by type: "product" or "service"
If null, returns all types (backward compatible)
 */
Type?: string;
/**
 * Filter by service category (only applies when type='service')
Values: ancestor-worship, opening-ceremony, wedding, buddha-worship, new-house, feng-shui-consultation
 */
ServiceCategory?: string;
};
