/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

export type GetApiV1CustomerAdminIdOrdersParams = {
/**
 * @minimum 1
 * @maximum 2147483647
 */
Page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
PageSize?: number;
/**
 * Sort by field: "Name", "Email", "CreatedAt", "LoyaltyPoints", "Tier"
 * @maxLength 50
 */
SortBy?: string;
/**
 * Sort descending (true) or ascending (false)
 */
SortDescending?: boolean;
/**
 * Calculate skip count for pagination
 */
Skip?: number;
};
