/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CRMInteractionType } from './cRMInteractionType';
import type { CRMInteractionStatus } from './cRMInteractionStatus';

export type GetApiV1CustomerAdminIdInteractionsParams = {
/**
 * @minimum 1
 * @maximum 2147483647
 */
Page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
PageSize?: number;
/**
 * Sort by field: "Name", "Email", "CreatedAt", "LoyaltyPoints", "Tier"
 * @maxLength 50
 */
SortBy?: string;
/**
 * Sort descending (true) or ascending (false)
 */
SortDescending?: boolean;
/**
 * Calculate skip count for pagination
 */
Skip?: number;
/**
 * Filter by customer ID
 */
CustomerId?: string;
/**
 * Filter by interaction type
 */
Type?: CRMInteractionType;
/**
 * Filter by interaction status
 */
Status?: CRMInteractionStatus;
/**
 * Search by Title or Description (partial match, case-insensitive)
 * @maxLength 100
 */
SearchTerm?: string;
/**
 * Filter interactions created on or after this date
 */
FromDate?: string;
/**
 * Filter interactions created on or before this date
 */
ToDate?: string;
/**
 * Filter by follow-up date range start
 */
FollowUpFromDate?: string;
/**
 * Filter by follow-up date range end
 */
FollowUpToDate?: string;
/**
 * Filter by creator user ID
 */
CreatedBy?: string;
/**
 * Filter interactions with pending follow-ups
 */
HasPendingFollowUp?: boolean;
};
