/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

export type GetApiV1PostsFeedParams = {
/**
 * Số trang (default: 1)
 */
pageNumber?: number;
/**
 * Số items mỗi trang (default: 20)
 */
pageSize?: number;
};
