/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export type GetApiV1CustomerAdminIdOrdersParams = {
/**
 * @minimum 1
 * @maximum 2147483647
 */
Page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
PageSize?: number;
/**
 * @maxLength 50
 */
SortBy?: string;
SortDescending?: boolean;
Skip?: number;
};
