/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export type GetApiV1MixedFeedParams = {
PageNumber?: number;
PageSize?: number;
MarketingRatio?: number;
Location?: string;
FeaturedOnly?: boolean;
ProductId?: string;
MinPriorityScore?: number;
};
