/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

export type GetApiV1OrderStatsRevenueParams = {
/**
 * Optional store filter
 */
storeId?: string;
/**
 * Optional start date
 */
fromDate?: string;
/**
 * Optional end date
 */
toDate?: string;
};
