/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * DTO for explanation of a single recommended item
 */
export interface ItemExplanationDto {
  /** Product ID being explained */
  productId?: string;
  /**
   * Product name
   * @nullable
   */
  productName?: string | null;
  /**
   * Why this item is needed for the ritual
   * @nullable
   */
  whyNeeded?: string | null;
  /**
   * Traditional usage and cultural significance of the item
   * @nullable
   */
  traditionalUsage?: string | null;
}
