/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { MixedFeedDto } from './mixedFeedDto';

/**
 * Result cho location-based posts
 */
export interface LocationPostsDto {
  /** @nullable */
  location?: string | null;
  /** @nullable */
  posts?: MixedFeedDto[] | null;
  totalCount?: number;
}
