/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { OrderDetailDtoPaginatedResult } from './orderDetailDtoPaginatedResult';

export interface OrderDetailDtoPaginatedResultApiResponse {
  success?: boolean;
  data?: OrderDetailDtoPaginatedResult;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
