/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { ShippingMethodEnum } from './shippingMethodEnum';

export interface OrderShippingInputDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  recipientName: string;
  /**
   * @minLength 1
   * @pattern ^[0-9]{10,11}$
   */
  phoneNumber: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  address: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  ward: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  district: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  city: string;
  /**
   * @maxLength 20
   * @nullable
   */
  postalCode?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  deliveryNote?: string | null;
  shippingMethod: ShippingMethodEnum;
}
