/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';

export interface OrderStatusHistoryDTO {
  status?: OrderStatus;
  /** @nullable */
  readonly statusText?: string | null;
  changedAt?: string;
  /** @nullable */
  changedByName?: string | null;
  /** @nullable */
  notes?: string | null;
}
