/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

export interface OrderShippingDto {
  /** @nullable */
  recipientName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  ward?: string | null;
  /** @nullable */
  district?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  shippingMethod?: string | null;
  shippingFee?: number;
  /** @nullable */
  shippingStatus?: string | null;
  /** @nullable */
  trackingNumber?: string | null;
  /** @nullable */
  carrier?: string | null;
  /** @nullable */
  shippedAt?: string | null;
  /** @nullable */
  deliveredAt?: string | null;
  /** @nullable */
  estimatedDelivery?: string | null;
}
