/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';
import type { OrderShippingDto } from './orderShippingDto';
import type { OrderItemDTO } from './orderItemDTO';
import type { OrderStatusHistoryDTO } from './orderStatusHistoryDTO';

export interface OrderDetailDto {
  orderId?: string;
  /** @nullable */
  orderNumber?: string | null;
  storeId?: string;
  /** @nullable */
  storeName?: string | null;
  customerId?: string;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  customerEmail?: string | null;
  /** @nullable */
  customerPhone?: string | null;
  status?: OrderStatus;
  /** @nullable */
  readonly statusText?: string | null;
  subTotal?: number;
  shippingFee?: number;
  taxAmount?: number;
  discountAmount?: number;
  totalAmount?: number;
  /** @nullable */
  notes?: string | null;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  completedAt?: string | null;
  /** @nullable */
  createdById?: string | null;
  /** @nullable */
  createdByName?: string | null;
  shipping?: OrderShippingDto;
  /** @nullable */
  items?: OrderItemDTO[] | null;
  readonly itemsCount?: number;
  /** @nullable */
  statusHistories?: OrderStatusHistoryDTO[] | null;
  isPaid?: boolean;
  /** @nullable */
  paidAmount?: number | null;
  /** @nullable */
  paymentMethod?: string | null;
  /** @nullable */
  paidAt?: string | null;
  /** @nullable */
  transactionId?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  serviceCategory?: string | null;
  /** @nullable */
  serviceDuration?: string | null;
  /** @nullable */
  serviceLocation?: string | null;
  /** @nullable */
  serviceDate?: string | null;
  /** @nullable */
  serviceNotes?: string | null;
}
