/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { PostFeedDto } from './postFeedDto';

export interface PostFeedDtoPaginatedResult {
  /** @nullable */
  items?: PostFeedDto[] | null;
  pageNumber?: number;
  pageSize?: number;
  totalItems?: number;
  totalPages?: number;
}
