/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CommentDtoPaginatedResult } from './commentDtoPaginatedResult';
import type { CustomerDto } from './customerDto';

export interface PostDetailDto {
  postId?: string;
  customerId?: string;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  customerAvatar?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  postedOn?: string;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  likesCount?: number;
  commentsCount?: number;
  bookmarksCount?: number;
  isLikedByCurrentUser?: boolean;
  isBookmarkedByCurrentUser?: boolean;
  isOwnedByCurrentUser?: boolean;
  comments?: CommentDtoPaginatedResult;
  /** @nullable */
  recentLikes?: CustomerDto[] | null;
}
