/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { ProductDetailDto } from './productDetailDto';

export interface ProductDetailDtoApiResponse {
  success?: boolean;
  data?: ProductDetailDto;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
