/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { DisplayPriceResult } from './displayPriceResult';

export interface ProductListDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  slug?: string | null;
  price?: number;
  /** @nullable */
  compareAtPrice?: number | null;
  displayPrice?: DisplayPriceResult;
  /** @nullable */
  readonly discountPercentage?: number | null;
  stockQuantity?: number;
  readonly inStock?: boolean;
  /** @nullable */
  primaryImage?: string | null;
  isActive?: boolean;
  isFeatured?: boolean;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  categoryName?: string | null;
  viewCount?: number;
  favoriteCount?: number;
  averageRating?: number;
  createdAt?: string;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  serviceCategory?: string | null;
  /** @nullable */
  serviceDuration?: string | null;
  /** @nullable */
  serviceRating?: number | null;
}
