/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { CustomizableOptionDto } from './customizableOptionDto';

export interface ProductCreateDto {
  /**
   * @minLength 3
   * @maxLength 200
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  shortDescription?: string | null;
  /**
   * @minLength 0
   * @maxLength 5000
   * @nullable
   */
  description?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   */
  code: string;
  /** @minimum 0 */
  price: number;
  /**
   * @minimum 0
   * @nullable
   */
  compareAtPrice?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  cost?: number | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  brandId?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  sku?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  barcode?: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  stockQuantity?: number;
  isActive?: boolean;
  isFeatured?: boolean;
  /** @nullable */
  images?: string[] | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  metaKeywords?: string | null;
  /**
   * List of fixed items included in a package product (e.g., "Cá chép (3 con)", "Mũ giấy (3 cái)").
Used for package products to describe what's included.
   * @nullable
   */
  details?: string[] | null;
  /**
   * List of customizable options for a package product.
Allows customers to modify quantities of specific items in the package.
   * @nullable
   */
  customizableOptions?: CustomizableOptionDto[] | null;
}
