/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * Request model for recording user interactions
 */
export interface RecordInteractionRequest {
  /**
   * Type of interaction: "viewed", "dismissed", or "clicked"
   * @nullable
   */
  interactionType?: string | null;
}
