/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export interface RegisterRequestDTO {
  /**
   * @minLength 0
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /** @minLength 1 */
  confirmPassword: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  storeId: string;
}
