/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { MixedFeedDto } from './mixedFeedDto';

export interface RelatedPostsDto {
  productId?: string;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  marketingPosts?: MixedFeedDto[] | null;
  /** @nullable */
  communityPosts?: MixedFeedDto[] | null;
  totalCount?: number;
}
