/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */

export interface StringDateTimeFAnonymousType8 {
  /** @nullable */
  status?: string | null;
  timestamp?: string;
}
