/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API
 * OpenAPI spec version: v1
 */
import type { ToggleWishlistResponse } from './toggleWishlistResponse';

export interface ToggleWishlistResponseApiResponse {
  success?: boolean;
  data?: ToggleWishlistResponse;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
