/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */

/**
 * DTO for tracking campaign impression
Requirements: 7.1
 */
export interface TrackImpressionDto {
  /**
   * Session ID of the user viewing the campaign
   * @nullable
   */
  sessionId?: string | null;
  /**
   * Page where the campaign was shown
   * @nullable
   */
  page?: string | null;
  /**
   * Timestamp when the impression was recorded
   * @nullable
   */
  recordedAt?: string | null;
}
