/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce API
 * VietCommerce E-commerce Platform API - Campaign & Promotion Management System
 * OpenAPI spec version: v1
 */
import type { WishlistItemDto } from './wishlistItemDto';

export interface WishlistItemDtoListApiResponse {
  success?: boolean;
  /** @nullable */
  data?: WishlistItemDto[] | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  errors?: string[] | null;
}
