/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseHRMWorkScheduleDto,
  ApiResponseObject,
  ApiResponsePaginatedResponseHRMWorkScheduleDto,
  GetApiWorkSchedulesParams,
  HRMCreateWorkScheduleRequest,
  HRMUpdateWorkScheduleRequest
} from '.././schemas';

import { apiClient } from '../../../src/lib/api/orval-client';




/**
 * **Permissions Required:**
- `hrm.schedule.view`
            
**Query Parameters:**
- Page, PageSize
- EmployeeId, StoreId, Department
- DateFrom, DateTo
- ShiftType (Morning, Afternoon, FullDay, etc.)
- Status (Approved, Pending, Rejected)
- Search (tìm theo tên nhân viên, mã lịch...)
            
**Response:** Paginated list of work schedules
 * @summary Lấy danh sách lịch làm việc (phân trang + lọc)
 */
export const getApiWorkSchedules = (
    params?: GetApiWorkSchedulesParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseHRMWorkScheduleDto>(
      {url: `/api/WorkSchedules`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiWorkSchedulesQueryKey = (params?: GetApiWorkSchedulesParams,) => {
    return [
    `/api/WorkSchedules`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiWorkSchedulesQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkSchedules>>, TError = ApiResponseObject>(params?: GetApiWorkSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedules>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkSchedulesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkSchedules>>> = ({ signal }) => getApiWorkSchedules(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkSchedulesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkSchedules>>>
export type GetApiWorkSchedulesQueryError = ApiResponseObject


export function useGetApiWorkSchedules<TData = Awaited<ReturnType<typeof getApiWorkSchedules>>, TError = ApiResponseObject>(
 params: undefined |  GetApiWorkSchedulesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkSchedules>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkSchedules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkSchedules<TData = Awaited<ReturnType<typeof getApiWorkSchedules>>, TError = ApiResponseObject>(
 params?: GetApiWorkSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkSchedules>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkSchedules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkSchedules<TData = Awaited<ReturnType<typeof getApiWorkSchedules>>, TError = ApiResponseObject>(
 params?: GetApiWorkSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedules>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lấy danh sách lịch làm việc (phân trang + lọc)
 */

export function useGetApiWorkSchedules<TData = Awaited<ReturnType<typeof getApiWorkSchedules>>, TError = ApiResponseObject>(
 params?: GetApiWorkSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedules>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkSchedulesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * **Permission Required:** `hrm.schedule.manage`
 * @summary Tạo mới lịch làm việc
 */
export const postApiWorkSchedules = (
    hRMCreateWorkScheduleRequest: HRMCreateWorkScheduleRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseHRMWorkScheduleDto>(
      {url: `/api/WorkSchedules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hRMCreateWorkScheduleRequest, signal
    },
      );
    }
  


export const getPostApiWorkSchedulesMutationOptions = <TError = ApiResponseObject,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkSchedules>>, TError,{data: HRMCreateWorkScheduleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkSchedules>>, TError,{data: HRMCreateWorkScheduleRequest}, TContext> => {

const mutationKey = ['postApiWorkSchedules'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkSchedules>>, {data: HRMCreateWorkScheduleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiWorkSchedules(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkSchedulesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkSchedules>>>
    export type PostApiWorkSchedulesMutationBody = HRMCreateWorkScheduleRequest
    export type PostApiWorkSchedulesMutationError = ApiResponseObject

    /**
 * @summary Tạo mới lịch làm việc
 */
export const usePostApiWorkSchedules = <TError = ApiResponseObject,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkSchedules>>, TError,{data: HRMCreateWorkScheduleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkSchedules>>,
        TError,
        {data: HRMCreateWorkScheduleRequest},
        TContext
      > => {

      const mutationOptions = getPostApiWorkSchedulesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Lấy chi tiết lịch làm việc theo ID
 */
export const getApiWorkSchedulesId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseHRMWorkScheduleDto>(
      {url: `/api/WorkSchedules/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiWorkSchedulesIdQueryKey = (id?: string,) => {
    return [
    `/api/WorkSchedules/${id}`
    ] as const;
    }

    
export const getGetApiWorkSchedulesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError = ApiResponseObject>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkSchedulesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkSchedulesId>>> = ({ signal }) => getApiWorkSchedulesId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkSchedulesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkSchedulesId>>>
export type GetApiWorkSchedulesIdQueryError = ApiResponseObject


export function useGetApiWorkSchedulesId<TData = Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError = ApiResponseObject>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkSchedulesId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkSchedulesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkSchedulesId<TData = Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError = ApiResponseObject>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkSchedulesId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkSchedulesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkSchedulesId<TData = Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError = ApiResponseObject>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lấy chi tiết lịch làm việc theo ID
 */

export function useGetApiWorkSchedulesId<TData = Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError = ApiResponseObject>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkSchedulesId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkSchedulesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * **Permission Required:** `hrm.schedule.manage`
 * @summary Cập nhật lịch làm việc
 */
export const putApiWorkSchedulesId = (
    id: string,
    hRMUpdateWorkScheduleRequest: HRMUpdateWorkScheduleRequest,
 ) => {
      
      
      return apiClient<ApiResponseHRMWorkScheduleDto>(
      {url: `/api/WorkSchedules/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: hRMUpdateWorkScheduleRequest
    },
      );
    }
  


export const getPutApiWorkSchedulesIdMutationOptions = <TError = ApiResponseObject,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkSchedulesId>>, TError,{id: string;data: HRMUpdateWorkScheduleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiWorkSchedulesId>>, TError,{id: string;data: HRMUpdateWorkScheduleRequest}, TContext> => {

const mutationKey = ['putApiWorkSchedulesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiWorkSchedulesId>>, {id: string;data: HRMUpdateWorkScheduleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiWorkSchedulesId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiWorkSchedulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiWorkSchedulesId>>>
    export type PutApiWorkSchedulesIdMutationBody = HRMUpdateWorkScheduleRequest
    export type PutApiWorkSchedulesIdMutationError = ApiResponseObject

    /**
 * @summary Cập nhật lịch làm việc
 */
export const usePutApiWorkSchedulesId = <TError = ApiResponseObject,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkSchedulesId>>, TError,{id: string;data: HRMUpdateWorkScheduleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiWorkSchedulesId>>,
        TError,
        {id: string;data: HRMUpdateWorkScheduleRequest},
        TContext
      > => {

      const mutationOptions = getPutApiWorkSchedulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * **Permission Required:** `hrm.schedule.manage`
 * @summary Xóa lịch làm việc
 */
export const deleteApiWorkSchedulesId = (
    id: string,
 ) => {
      
      
      return apiClient<void>(
      {url: `/api/WorkSchedules/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiWorkSchedulesIdMutationOptions = <TError = ApiResponseObject,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkSchedulesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkSchedulesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiWorkSchedulesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiWorkSchedulesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiWorkSchedulesId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiWorkSchedulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiWorkSchedulesId>>>
    
    export type DeleteApiWorkSchedulesIdMutationError = ApiResponseObject

    /**
 * @summary Xóa lịch làm việc
 */
export const useDeleteApiWorkSchedulesId = <TError = ApiResponseObject,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkSchedulesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiWorkSchedulesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiWorkSchedulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    