/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddressCreateCustomerAddressRequest,
  AddressUpdateCustomerAddressRequest,
  ApiResponseAddressCustomerAddressDto,
  ApiResponseBoolean,
  ApiResponseCRMCRMInteractionDto,
  ApiResponseCustomersCustomerDetailDto,
  ApiResponseCustomersCustomerOrderSummaryDto,
  ApiResponseCustomersCustomerStatisticsDto,
  ApiResponseListAddressCustomerAddressDto,
  ApiResponseListCRMCRMInteractionListDto,
  ApiResponseListCustomersCustomerListDto,
  ApiResponseListCustomersLoyaltyHistoryDto,
  ApiResponsePaginatedResponseCRMCRMInteractionListDto,
  ApiResponsePaginatedResponseCustomersCustomerListDto,
  ApiResponsePaginatedResponseOrdersOrderDetailDto,
  CRMCreateInteractionRequest,
  CRMUpdateInteractionRequest,
  CustomersAddPointsRequest,
  CustomersCreateCustomerRequest,
  CustomersDeductPointsRequest,
  CustomersUpdateCustomerRequest,
  CustomersUpdateTierRequest,
  GetApiV1CustomerAdminIdInteractionsParams,
  GetApiV1CustomerAdminIdOrdersParams,
  GetApiV1CustomerAdminInteractionsUpcomingParams,
  GetApiV1CustomerAdminParams,
  GetApiV1CustomerAdminSearchParams
} from '.././schemas';

import { apiClient } from '../../../src/lib/api/orval-client';




export const getApiV1CustomerAdmin = (
    params?: GetApiV1CustomerAdminParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseCustomersCustomerListDto>(
      {url: `/api/v1/CustomerAdmin`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminQueryKey = (params?: GetApiV1CustomerAdminParams,) => {
    return [
    `/api/v1/CustomerAdmin`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CustomerAdminQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError = unknown>(params?: GetApiV1CustomerAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>> = ({ signal }) => getApiV1CustomerAdmin(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>>
export type GetApiV1CustomerAdminQueryError = unknown


export function useGetApiV1CustomerAdmin<TData = Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError = unknown>(
 params: undefined |  GetApiV1CustomerAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdmin<TData = Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError = unknown>(
 params?: GetApiV1CustomerAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdmin<TData = Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError = unknown>(
 params?: GetApiV1CustomerAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdmin<TData = Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError = unknown>(
 params?: GetApiV1CustomerAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiV1CustomerAdmin = (
    customersCreateCustomerRequest: CustomersCreateCustomerRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/v1/CustomerAdmin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customersCreateCustomerRequest, signal
    },
      );
    }
  


export const getPostApiV1CustomerAdminMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdmin>>, TError,{data: CustomersCreateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdmin>>, TError,{data: CustomersCreateCustomerRequest}, TContext> => {

const mutationKey = ['postApiV1CustomerAdmin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CustomerAdmin>>, {data: CustomersCreateCustomerRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CustomerAdmin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CustomerAdminMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CustomerAdmin>>>
    export type PostApiV1CustomerAdminMutationBody = CustomersCreateCustomerRequest
    export type PostApiV1CustomerAdminMutationError = unknown

    export const usePostApiV1CustomerAdmin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdmin>>, TError,{data: CustomersCreateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CustomerAdmin>>,
        TError,
        {data: CustomersCreateCustomerRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CustomerAdminMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/v1/CustomerAdmin/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/CustomerAdmin/${id}`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>> = ({ signal }) => getApiV1CustomerAdminId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>>
export type GetApiV1CustomerAdminIdQueryError = unknown


export function useGetApiV1CustomerAdminId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1CustomerAdminId = (
    id: string,
    customersUpdateCustomerRequest: CustomersUpdateCustomerRequest,
 ) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/v1/CustomerAdmin/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: customersUpdateCustomerRequest
    },
      );
    }
  


export const getPutApiV1CustomerAdminIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminId>>, TError,{id: string;data: CustomersUpdateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminId>>, TError,{id: string;data: CustomersUpdateCustomerRequest}, TContext> => {

const mutationKey = ['putApiV1CustomerAdminId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CustomerAdminId>>, {id: string;data: CustomersUpdateCustomerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1CustomerAdminId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CustomerAdminIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CustomerAdminId>>>
    export type PutApiV1CustomerAdminIdMutationBody = CustomersUpdateCustomerRequest
    export type PutApiV1CustomerAdminIdMutationError = unknown

    export const usePutApiV1CustomerAdminId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminId>>, TError,{id: string;data: CustomersUpdateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CustomerAdminId>>,
        TError,
        {id: string;data: CustomersUpdateCustomerRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1CustomerAdminIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiV1CustomerAdminId = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/CustomerAdmin/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1CustomerAdminIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1CustomerAdminId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CustomerAdminId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1CustomerAdminId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CustomerAdminIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CustomerAdminId>>>
    
    export type DeleteApiV1CustomerAdminIdMutationError = unknown

    export const useDeleteApiV1CustomerAdminId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CustomerAdminId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CustomerAdminIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminIdAddresses = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListAddressCustomerAddressDto>(
      {url: `/api/v1/CustomerAdmin/${id}/addresses`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdAddressesQueryKey = (id?: string,) => {
    return [
    `/api/v1/CustomerAdmin/${id}/addresses`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdAddressesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdAddressesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>> = ({ signal }) => getApiV1CustomerAdminIdAddresses(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdAddressesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>>
export type GetApiV1CustomerAdminIdAddressesQueryError = unknown


export function useGetApiV1CustomerAdminIdAddresses<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdAddresses<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdAddresses<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminIdAddresses<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdAddresses>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdAddressesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1CustomerAdminIdAddressesAddressIdDefault = (
    id: string,
    addressId: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/CustomerAdmin/${id}/addresses/${addressId}/default`, method: 'PUT'
    },
      );
    }
  


export const getPutApiV1CustomerAdminIdAddressesAddressIdDefaultMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminIdAddressesAddressIdDefault>>, TError,{id: string;addressId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminIdAddressesAddressIdDefault>>, TError,{id: string;addressId: string}, TContext> => {

const mutationKey = ['putApiV1CustomerAdminIdAddressesAddressIdDefault'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CustomerAdminIdAddressesAddressIdDefault>>, {id: string;addressId: string}> = (props) => {
          const {id,addressId} = props ?? {};

          return  putApiV1CustomerAdminIdAddressesAddressIdDefault(id,addressId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CustomerAdminIdAddressesAddressIdDefaultMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CustomerAdminIdAddressesAddressIdDefault>>>
    
    export type PutApiV1CustomerAdminIdAddressesAddressIdDefaultMutationError = unknown

    export const usePutApiV1CustomerAdminIdAddressesAddressIdDefault = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminIdAddressesAddressIdDefault>>, TError,{id: string;addressId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CustomerAdminIdAddressesAddressIdDefault>>,
        TError,
        {id: string;addressId: string},
        TContext
      > => {

      const mutationOptions = getPutApiV1CustomerAdminIdAddressesAddressIdDefaultMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminIdInteractions = (
    id: string,
    params?: GetApiV1CustomerAdminIdInteractionsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseCRMCRMInteractionListDto>(
      {url: `/api/v1/CustomerAdmin/${id}/interactions`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdInteractionsQueryKey = (id?: string,
    params?: GetApiV1CustomerAdminIdInteractionsParams,) => {
    return [
    `/api/v1/CustomerAdmin/${id}/interactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdInteractionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError = unknown>(id: string,
    params?: GetApiV1CustomerAdminIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdInteractionsQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>> = ({ signal }) => getApiV1CustomerAdminIdInteractions(id,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdInteractionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>>
export type GetApiV1CustomerAdminIdInteractionsQueryError = unknown


export function useGetApiV1CustomerAdminIdInteractions<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError = unknown>(
 id: string,
    params: undefined |  GetApiV1CustomerAdminIdInteractionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdInteractions<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError = unknown>(
 id: string,
    params?: GetApiV1CustomerAdminIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdInteractions<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError = unknown>(
 id: string,
    params?: GetApiV1CustomerAdminIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminIdInteractions<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError = unknown>(
 id: string,
    params?: GetApiV1CustomerAdminIdInteractionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdInteractions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdInteractionsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CustomerAdminIdLoyaltyHistory = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListCustomersLoyaltyHistoryDto>(
      {url: `/api/v1/CustomerAdmin/${id}/loyalty-history`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdLoyaltyHistoryQueryKey = (id?: string,) => {
    return [
    `/api/v1/CustomerAdmin/${id}/loyalty-history`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdLoyaltyHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdLoyaltyHistoryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>> = ({ signal }) => getApiV1CustomerAdminIdLoyaltyHistory(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdLoyaltyHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>>
export type GetApiV1CustomerAdminIdLoyaltyHistoryQueryError = unknown


export function useGetApiV1CustomerAdminIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminIdLoyaltyHistory<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdLoyaltyHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdLoyaltyHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiV1CustomerAdminIdLoyaltyAdd = (
    id: string,
    customersAddPointsRequest: CustomersAddPointsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/v1/CustomerAdmin/${id}/loyalty/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customersAddPointsRequest, signal
    },
      );
    }
  


export const getPostApiV1CustomerAdminIdLoyaltyAddMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyAdd>>, TError,{id: string;data: CustomersAddPointsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyAdd>>, TError,{id: string;data: CustomersAddPointsRequest}, TContext> => {

const mutationKey = ['postApiV1CustomerAdminIdLoyaltyAdd'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyAdd>>, {id: string;data: CustomersAddPointsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1CustomerAdminIdLoyaltyAdd(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CustomerAdminIdLoyaltyAddMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyAdd>>>
    export type PostApiV1CustomerAdminIdLoyaltyAddMutationBody = CustomersAddPointsRequest
    export type PostApiV1CustomerAdminIdLoyaltyAddMutationError = unknown

    export const usePostApiV1CustomerAdminIdLoyaltyAdd = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyAdd>>, TError,{id: string;data: CustomersAddPointsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyAdd>>,
        TError,
        {id: string;data: CustomersAddPointsRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CustomerAdminIdLoyaltyAddMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiV1CustomerAdminIdLoyaltyDeduct = (
    id: string,
    customersDeductPointsRequest: CustomersDeductPointsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/v1/CustomerAdmin/${id}/loyalty/deduct`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customersDeductPointsRequest, signal
    },
      );
    }
  


export const getPostApiV1CustomerAdminIdLoyaltyDeductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyDeduct>>, TError,{id: string;data: CustomersDeductPointsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyDeduct>>, TError,{id: string;data: CustomersDeductPointsRequest}, TContext> => {

const mutationKey = ['postApiV1CustomerAdminIdLoyaltyDeduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyDeduct>>, {id: string;data: CustomersDeductPointsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1CustomerAdminIdLoyaltyDeduct(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CustomerAdminIdLoyaltyDeductMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyDeduct>>>
    export type PostApiV1CustomerAdminIdLoyaltyDeductMutationBody = CustomersDeductPointsRequest
    export type PostApiV1CustomerAdminIdLoyaltyDeductMutationError = unknown

    export const usePostApiV1CustomerAdminIdLoyaltyDeduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyDeduct>>, TError,{id: string;data: CustomersDeductPointsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CustomerAdminIdLoyaltyDeduct>>,
        TError,
        {id: string;data: CustomersDeductPointsRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CustomerAdminIdLoyaltyDeductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminIdOrders = (
    id: string,
    params?: GetApiV1CustomerAdminIdOrdersParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResponseOrdersOrderDetailDto>(
      {url: `/api/v1/CustomerAdmin/${id}/orders`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdOrdersQueryKey = (id?: string,
    params?: GetApiV1CustomerAdminIdOrdersParams,) => {
    return [
    `/api/v1/CustomerAdmin/${id}/orders`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError = unknown>(id: string,
    params?: GetApiV1CustomerAdminIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdOrdersQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>> = ({ signal }) => getApiV1CustomerAdminIdOrders(id,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>>
export type GetApiV1CustomerAdminIdOrdersQueryError = unknown


export function useGetApiV1CustomerAdminIdOrders<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError = unknown>(
 id: string,
    params: undefined |  GetApiV1CustomerAdminIdOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdOrders<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError = unknown>(
 id: string,
    params?: GetApiV1CustomerAdminIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdOrders<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError = unknown>(
 id: string,
    params?: GetApiV1CustomerAdminIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminIdOrders<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError = unknown>(
 id: string,
    params?: GetApiV1CustomerAdminIdOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrders>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdOrdersQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CustomerAdminIdOrdersSummary = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerOrderSummaryDto>(
      {url: `/api/v1/CustomerAdmin/${id}/orders/summary`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdOrdersSummaryQueryKey = (id?: string,) => {
    return [
    `/api/v1/CustomerAdmin/${id}/orders/summary`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdOrdersSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdOrdersSummaryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>> = ({ signal }) => getApiV1CustomerAdminIdOrdersSummary(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdOrdersSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>>
export type GetApiV1CustomerAdminIdOrdersSummaryQueryError = unknown


export function useGetApiV1CustomerAdminIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminIdOrdersSummary<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdOrdersSummary>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdOrdersSummaryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CustomerAdminIdStatistics = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCustomersCustomerStatisticsDto>(
      {url: `/api/v1/CustomerAdmin/${id}/statistics`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminIdStatisticsQueryKey = (id?: string,) => {
    return [
    `/api/v1/CustomerAdmin/${id}/statistics`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminIdStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminIdStatisticsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>> = ({ signal }) => getApiV1CustomerAdminIdStatistics(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminIdStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>>
export type GetApiV1CustomerAdminIdStatisticsQueryError = unknown


export function useGetApiV1CustomerAdminIdStatistics<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdStatistics<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminIdStatistics<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminIdStatistics<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminIdStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminIdStatisticsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1CustomerAdminIdTier = (
    id: string,
    customersUpdateTierRequest: CustomersUpdateTierRequest,
 ) => {
      
      
      return apiClient<ApiResponseCustomersCustomerDetailDto>(
      {url: `/api/v1/CustomerAdmin/${id}/tier`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: customersUpdateTierRequest
    },
      );
    }
  


export const getPutApiV1CustomerAdminIdTierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminIdTier>>, TError,{id: string;data: CustomersUpdateTierRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminIdTier>>, TError,{id: string;data: CustomersUpdateTierRequest}, TContext> => {

const mutationKey = ['putApiV1CustomerAdminIdTier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CustomerAdminIdTier>>, {id: string;data: CustomersUpdateTierRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1CustomerAdminIdTier(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CustomerAdminIdTierMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CustomerAdminIdTier>>>
    export type PutApiV1CustomerAdminIdTierMutationBody = CustomersUpdateTierRequest
    export type PutApiV1CustomerAdminIdTierMutationError = unknown

    export const usePutApiV1CustomerAdminIdTier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminIdTier>>, TError,{id: string;data: CustomersUpdateTierRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CustomerAdminIdTier>>,
        TError,
        {id: string;data: CustomersUpdateTierRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1CustomerAdminIdTierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiV1CustomerAdminAddresses = (
    addressCreateCustomerAddressRequest: AddressCreateCustomerAddressRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseAddressCustomerAddressDto>(
      {url: `/api/v1/CustomerAdmin/addresses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addressCreateCustomerAddressRequest, signal
    },
      );
    }
  


export const getPostApiV1CustomerAdminAddressesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminAddresses>>, TError,{data: AddressCreateCustomerAddressRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminAddresses>>, TError,{data: AddressCreateCustomerAddressRequest}, TContext> => {

const mutationKey = ['postApiV1CustomerAdminAddresses'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CustomerAdminAddresses>>, {data: AddressCreateCustomerAddressRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CustomerAdminAddresses(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CustomerAdminAddressesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CustomerAdminAddresses>>>
    export type PostApiV1CustomerAdminAddressesMutationBody = AddressCreateCustomerAddressRequest
    export type PostApiV1CustomerAdminAddressesMutationError = unknown

    export const usePostApiV1CustomerAdminAddresses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminAddresses>>, TError,{data: AddressCreateCustomerAddressRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CustomerAdminAddresses>>,
        TError,
        {data: AddressCreateCustomerAddressRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CustomerAdminAddressesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminAddressesAddressId = (
    addressId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseAddressCustomerAddressDto>(
      {url: `/api/v1/CustomerAdmin/addresses/${addressId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminAddressesAddressIdQueryKey = (addressId?: string,) => {
    return [
    `/api/v1/CustomerAdmin/addresses/${addressId}`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminAddressesAddressIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError = unknown>(addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminAddressesAddressIdQueryKey(addressId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>> = ({ signal }) => getApiV1CustomerAdminAddressesAddressId(addressId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(addressId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminAddressesAddressIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>>
export type GetApiV1CustomerAdminAddressesAddressIdQueryError = unknown


export function useGetApiV1CustomerAdminAddressesAddressId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError = unknown>(
 addressId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminAddressesAddressId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError = unknown>(
 addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminAddressesAddressId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError = unknown>(
 addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminAddressesAddressId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError = unknown>(
 addressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminAddressesAddressId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminAddressesAddressIdQueryOptions(addressId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1CustomerAdminAddressesAddressId = (
    addressId: string,
    addressUpdateCustomerAddressRequest: AddressUpdateCustomerAddressRequest,
 ) => {
      
      
      return apiClient<ApiResponseAddressCustomerAddressDto>(
      {url: `/api/v1/CustomerAdmin/addresses/${addressId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addressUpdateCustomerAddressRequest
    },
      );
    }
  


export const getPutApiV1CustomerAdminAddressesAddressIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminAddressesAddressId>>, TError,{addressId: string;data: AddressUpdateCustomerAddressRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminAddressesAddressId>>, TError,{addressId: string;data: AddressUpdateCustomerAddressRequest}, TContext> => {

const mutationKey = ['putApiV1CustomerAdminAddressesAddressId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CustomerAdminAddressesAddressId>>, {addressId: string;data: AddressUpdateCustomerAddressRequest}> = (props) => {
          const {addressId,data} = props ?? {};

          return  putApiV1CustomerAdminAddressesAddressId(addressId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CustomerAdminAddressesAddressIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CustomerAdminAddressesAddressId>>>
    export type PutApiV1CustomerAdminAddressesAddressIdMutationBody = AddressUpdateCustomerAddressRequest
    export type PutApiV1CustomerAdminAddressesAddressIdMutationError = unknown

    export const usePutApiV1CustomerAdminAddressesAddressId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminAddressesAddressId>>, TError,{addressId: string;data: AddressUpdateCustomerAddressRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CustomerAdminAddressesAddressId>>,
        TError,
        {addressId: string;data: AddressUpdateCustomerAddressRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1CustomerAdminAddressesAddressIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiV1CustomerAdminAddressesAddressId = (
    addressId: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/CustomerAdmin/addresses/${addressId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1CustomerAdminAddressesAddressIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminAddressesAddressId>>, TError,{addressId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminAddressesAddressId>>, TError,{addressId: string}, TContext> => {

const mutationKey = ['deleteApiV1CustomerAdminAddressesAddressId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CustomerAdminAddressesAddressId>>, {addressId: string}> = (props) => {
          const {addressId} = props ?? {};

          return  deleteApiV1CustomerAdminAddressesAddressId(addressId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CustomerAdminAddressesAddressIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CustomerAdminAddressesAddressId>>>
    
    export type DeleteApiV1CustomerAdminAddressesAddressIdMutationError = unknown

    export const useDeleteApiV1CustomerAdminAddressesAddressId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminAddressesAddressId>>, TError,{addressId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CustomerAdminAddressesAddressId>>,
        TError,
        {addressId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CustomerAdminAddressesAddressIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiV1CustomerAdminInteractions = (
    cRMCreateInteractionRequest: CRMCreateInteractionRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/v1/CustomerAdmin/interactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cRMCreateInteractionRequest, signal
    },
      );
    }
  


export const getPostApiV1CustomerAdminInteractionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminInteractions>>, TError,{data: CRMCreateInteractionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminInteractions>>, TError,{data: CRMCreateInteractionRequest}, TContext> => {

const mutationKey = ['postApiV1CustomerAdminInteractions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CustomerAdminInteractions>>, {data: CRMCreateInteractionRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CustomerAdminInteractions(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CustomerAdminInteractionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CustomerAdminInteractions>>>
    export type PostApiV1CustomerAdminInteractionsMutationBody = CRMCreateInteractionRequest
    export type PostApiV1CustomerAdminInteractionsMutationError = unknown

    export const usePostApiV1CustomerAdminInteractions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CustomerAdminInteractions>>, TError,{data: CRMCreateInteractionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CustomerAdminInteractions>>,
        TError,
        {data: CRMCreateInteractionRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CustomerAdminInteractionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminInteractionsInteractionId = (
    interactionId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/v1/CustomerAdmin/interactions/${interactionId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminInteractionsInteractionIdQueryKey = (interactionId?: string,) => {
    return [
    `/api/v1/CustomerAdmin/interactions/${interactionId}`
    ] as const;
    }

    
export const getGetApiV1CustomerAdminInteractionsInteractionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError = unknown>(interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminInteractionsInteractionIdQueryKey(interactionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>> = ({ signal }) => getApiV1CustomerAdminInteractionsInteractionId(interactionId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(interactionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminInteractionsInteractionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>>
export type GetApiV1CustomerAdminInteractionsInteractionIdQueryError = unknown


export function useGetApiV1CustomerAdminInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminInteractionsInteractionId<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError = unknown>(
 interactionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsInteractionId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminInteractionsInteractionIdQueryOptions(interactionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1CustomerAdminInteractionsInteractionId = (
    interactionId: string,
    cRMUpdateInteractionRequest: CRMUpdateInteractionRequest,
 ) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/v1/CustomerAdmin/interactions/${interactionId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: cRMUpdateInteractionRequest
    },
      );
    }
  


export const getPutApiV1CustomerAdminInteractionsInteractionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionId>>, TError,{interactionId: string;data: CRMUpdateInteractionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionId>>, TError,{interactionId: string;data: CRMUpdateInteractionRequest}, TContext> => {

const mutationKey = ['putApiV1CustomerAdminInteractionsInteractionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionId>>, {interactionId: string;data: CRMUpdateInteractionRequest}> = (props) => {
          const {interactionId,data} = props ?? {};

          return  putApiV1CustomerAdminInteractionsInteractionId(interactionId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CustomerAdminInteractionsInteractionIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionId>>>
    export type PutApiV1CustomerAdminInteractionsInteractionIdMutationBody = CRMUpdateInteractionRequest
    export type PutApiV1CustomerAdminInteractionsInteractionIdMutationError = unknown

    export const usePutApiV1CustomerAdminInteractionsInteractionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionId>>, TError,{interactionId: string;data: CRMUpdateInteractionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionId>>,
        TError,
        {interactionId: string;data: CRMUpdateInteractionRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1CustomerAdminInteractionsInteractionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiV1CustomerAdminInteractionsInteractionId = (
    interactionId: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/CustomerAdmin/interactions/${interactionId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1CustomerAdminInteractionsInteractionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminInteractionsInteractionId>>, TError,{interactionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminInteractionsInteractionId>>, TError,{interactionId: string}, TContext> => {

const mutationKey = ['deleteApiV1CustomerAdminInteractionsInteractionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CustomerAdminInteractionsInteractionId>>, {interactionId: string}> = (props) => {
          const {interactionId} = props ?? {};

          return  deleteApiV1CustomerAdminInteractionsInteractionId(interactionId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CustomerAdminInteractionsInteractionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CustomerAdminInteractionsInteractionId>>>
    
    export type DeleteApiV1CustomerAdminInteractionsInteractionIdMutationError = unknown

    export const useDeleteApiV1CustomerAdminInteractionsInteractionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CustomerAdminInteractionsInteractionId>>, TError,{interactionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CustomerAdminInteractionsInteractionId>>,
        TError,
        {interactionId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CustomerAdminInteractionsInteractionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const putApiV1CustomerAdminInteractionsInteractionIdComplete = (
    interactionId: string,
 ) => {
      
      
      return apiClient<ApiResponseCRMCRMInteractionDto>(
      {url: `/api/v1/CustomerAdmin/interactions/${interactionId}/complete`, method: 'PUT'
    },
      );
    }
  


export const getPutApiV1CustomerAdminInteractionsInteractionIdCompleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionIdComplete>>, TError,{interactionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionIdComplete>>, TError,{interactionId: string}, TContext> => {

const mutationKey = ['putApiV1CustomerAdminInteractionsInteractionIdComplete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionIdComplete>>, {interactionId: string}> = (props) => {
          const {interactionId} = props ?? {};

          return  putApiV1CustomerAdminInteractionsInteractionIdComplete(interactionId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CustomerAdminInteractionsInteractionIdCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionIdComplete>>>
    
    export type PutApiV1CustomerAdminInteractionsInteractionIdCompleteMutationError = unknown

    export const usePutApiV1CustomerAdminInteractionsInteractionIdComplete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionIdComplete>>, TError,{interactionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CustomerAdminInteractionsInteractionIdComplete>>,
        TError,
        {interactionId: string},
        TContext
      > => {

      const mutationOptions = getPutApiV1CustomerAdminInteractionsInteractionIdCompleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CustomerAdminInteractionsUpcoming = (
    params?: GetApiV1CustomerAdminInteractionsUpcomingParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListCRMCRMInteractionListDto>(
      {url: `/api/v1/CustomerAdmin/interactions/upcoming`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminInteractionsUpcomingQueryKey = (params?: GetApiV1CustomerAdminInteractionsUpcomingParams,) => {
    return [
    `/api/v1/CustomerAdmin/interactions/upcoming`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CustomerAdminInteractionsUpcomingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError = unknown>(params?: GetApiV1CustomerAdminInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminInteractionsUpcomingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>> = ({ signal }) => getApiV1CustomerAdminInteractionsUpcoming(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminInteractionsUpcomingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>>
export type GetApiV1CustomerAdminInteractionsUpcomingQueryError = unknown


export function useGetApiV1CustomerAdminInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError = unknown>(
 params: undefined |  GetApiV1CustomerAdminInteractionsUpcomingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError = unknown>(
 params?: GetApiV1CustomerAdminInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError = unknown>(
 params?: GetApiV1CustomerAdminInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminInteractionsUpcoming<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError = unknown>(
 params?: GetApiV1CustomerAdminInteractionsUpcomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminInteractionsUpcoming>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminInteractionsUpcomingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CustomerAdminSearch = (
    params?: GetApiV1CustomerAdminSearchParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseListCustomersCustomerListDto>(
      {url: `/api/v1/CustomerAdmin/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CustomerAdminSearchQueryKey = (params?: GetApiV1CustomerAdminSearchParams,) => {
    return [
    `/api/v1/CustomerAdmin/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CustomerAdminSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError = unknown>(params?: GetApiV1CustomerAdminSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CustomerAdminSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>> = ({ signal }) => getApiV1CustomerAdminSearch(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CustomerAdminSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>>
export type GetApiV1CustomerAdminSearchQueryError = unknown


export function useGetApiV1CustomerAdminSearch<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError = unknown>(
 params: undefined |  GetApiV1CustomerAdminSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminSearch<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError = unknown>(
 params?: GetApiV1CustomerAdminSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CustomerAdminSearch<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError = unknown>(
 params?: GetApiV1CustomerAdminSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CustomerAdminSearch<TData = Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError = unknown>(
 params?: GetApiV1CustomerAdminSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CustomerAdminSearch>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CustomerAdminSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




