/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseBoolean,
  ApiResponseCategoryCategoryDetailDto,
  ApiResponseCategoryCategoryDto,
  ApiResponseIEnumerableCategoryCategoryDto,
  ApiResponseInt32,
  ApiResponsePaginatedResultCategoryCategoryDto,
  CategoryCreateCategoryDto,
  CategoryUpdateCategoryDto,
  GetApiCategoryExistsParams,
  GetApiCategoryPagedListParams,
  GetApiV1CategoryExistsParams,
  GetApiV1CategoryPagedListParams,
  PatchApiCategoryIdStatusParams,
  PatchApiV1CategoryIdStatusParams
} from '.././schemas';

import { apiClient } from '../../../src/lib/api/orval-client';




export const getApiCategory = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/Category`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryQueryKey = () => {
    return [
    `/api/Category`
    ] as const;
    }

    
export const getGetApiCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategory>>> = ({ signal }) => getApiCategory(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategory>>>
export type GetApiCategoryQueryError = unknown


export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategory>>,
          TError,
          Awaited<ReturnType<typeof getApiCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategory>>,
          TError,
          Awaited<ReturnType<typeof getApiCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiCategory = (
    categoryCreateCategoryDto: CategoryCreateCategoryDto,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDto>(
      {url: `/api/Category`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateCategoryDto, signal
    },
      );
    }
  


export const getPostApiCategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCategory>>, TError,{data: CategoryCreateCategoryDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCategory>>, TError,{data: CategoryCreateCategoryDto}, TContext> => {

const mutationKey = ['postApiCategory'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCategory>>, {data: CategoryCreateCategoryDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiCategory(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCategory>>>
    export type PostApiCategoryMutationBody = CategoryCreateCategoryDto
    export type PostApiCategoryMutationError = unknown

    export const usePostApiCategory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCategory>>, TError,{data: CategoryCreateCategoryDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCategory>>,
        TError,
        {data: CategoryCreateCategoryDto},
        TContext
      > => {

      const mutationOptions = getPostApiCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiCategoryId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDto>(
      {url: `/api/Category/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryIdQueryKey = (id?: string,) => {
    return [
    `/api/Category/${id}`
    ] as const;
    }

    
export const getGetApiCategoryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryId>>> = ({ signal }) => getApiCategoryId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryId>>>
export type GetApiCategoryIdQueryError = unknown


export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiCategoryId = (
    id: string,
    categoryUpdateCategoryDto: CategoryUpdateCategoryDto,
 ) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDto>(
      {url: `/api/Category/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryUpdateCategoryDto
    },
      );
    }
  


export const getPutApiCategoryIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCategoryId>>, TError,{id: string;data: CategoryUpdateCategoryDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiCategoryId>>, TError,{id: string;data: CategoryUpdateCategoryDto}, TContext> => {

const mutationKey = ['putApiCategoryId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCategoryId>>, {id: string;data: CategoryUpdateCategoryDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCategoryId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiCategoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCategoryId>>>
    export type PutApiCategoryIdMutationBody = CategoryUpdateCategoryDto
    export type PutApiCategoryIdMutationError = unknown

    export const usePutApiCategoryId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCategoryId>>, TError,{id: string;data: CategoryUpdateCategoryDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCategoryId>>,
        TError,
        {id: string;data: CategoryUpdateCategoryDto},
        TContext
      > => {

      const mutationOptions = getPutApiCategoryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiCategoryId = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Category/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiCategoryIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoryId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoryId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiCategoryId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCategoryId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCategoryId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCategoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCategoryId>>>
    
    export type DeleteApiCategoryIdMutationError = unknown

    export const useDeleteApiCategoryId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoryId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCategoryId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiCategoryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiCategoryIdDetails = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDetailDto>(
      {url: `/api/Category/${id}/details`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryIdDetailsQueryKey = (id?: string,) => {
    return [
    `/api/Category/${id}/details`
    ] as const;
    }

    
export const getGetApiCategoryIdDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryIdDetailsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryIdDetails>>> = ({ signal }) => getApiCategoryIdDetails(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryIdDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryIdDetails>>>
export type GetApiCategoryIdDetailsQueryError = unknown


export function useGetApiCategoryIdDetails<TData = Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryIdDetails>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryIdDetails>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryIdDetails<TData = Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryIdDetails>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryIdDetails>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryIdDetails<TData = Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryIdDetails<TData = Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdDetails>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryIdDetailsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiCategoryIdSoftDelete = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Category/${id}/soft-delete`, method: 'PATCH'
    },
      );
    }
  


export const getPatchApiCategoryIdSoftDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCategoryIdSoftDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCategoryIdSoftDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiCategoryIdSoftDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCategoryIdSoftDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiCategoryIdSoftDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCategoryIdSoftDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCategoryIdSoftDelete>>>
    
    export type PatchApiCategoryIdSoftDeleteMutationError = unknown

    export const usePatchApiCategoryIdSoftDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCategoryIdSoftDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCategoryIdSoftDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPatchApiCategoryIdSoftDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchApiCategoryIdStatus = (
    id: string,
    params?: PatchApiCategoryIdStatusParams,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Category/${id}/status`, method: 'PATCH',
        params
    },
      );
    }
  


export const getPatchApiCategoryIdStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCategoryIdStatus>>, TError,{id: string;params?: PatchApiCategoryIdStatusParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCategoryIdStatus>>, TError,{id: string;params?: PatchApiCategoryIdStatusParams}, TContext> => {

const mutationKey = ['patchApiCategoryIdStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCategoryIdStatus>>, {id: string;params?: PatchApiCategoryIdStatusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  patchApiCategoryIdStatus(id,params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCategoryIdStatusMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCategoryIdStatus>>>
    
    export type PatchApiCategoryIdStatusMutationError = unknown

    export const usePatchApiCategoryIdStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCategoryIdStatus>>, TError,{id: string;params?: PatchApiCategoryIdStatusParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCategoryIdStatus>>,
        TError,
        {id: string;params?: PatchApiCategoryIdStatusParams},
        TContext
      > => {

      const mutationOptions = getPatchApiCategoryIdStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiCategoryParentIdSubcategories = (
    parentId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/Category/${parentId}/subcategories`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryParentIdSubcategoriesQueryKey = (parentId?: string,) => {
    return [
    `/api/Category/${parentId}/subcategories`
    ] as const;
    }

    
export const getGetApiCategoryParentIdSubcategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError = unknown>(parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryParentIdSubcategoriesQueryKey(parentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>> = ({ signal }) => getApiCategoryParentIdSubcategories(parentId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(parentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryParentIdSubcategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>>
export type GetApiCategoryParentIdSubcategoriesQueryError = unknown


export function useGetApiCategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryParentIdSubcategories>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryParentIdSubcategoriesQueryOptions(parentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiCategoryActiveList = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/Category/active/list`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryActiveListQueryKey = () => {
    return [
    `/api/Category/active/list`
    ] as const;
    }

    
export const getGetApiCategoryActiveListQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryActiveListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryActiveList>>> = ({ signal }) => getApiCategoryActiveList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryActiveListQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryActiveList>>>
export type GetApiCategoryActiveListQueryError = unknown


export function useGetApiCategoryActiveList<TData = Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryActiveList>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryActiveList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryActiveList<TData = Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryActiveList>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryActiveList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryActiveList<TData = Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryActiveList<TData = Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryActiveList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryActiveListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiCategoryCountByStoreStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseInt32>(
      {url: `/api/Category/count/by-store/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryCountByStoreStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/Category/count/by-store/${storeId}`
    ] as const;
    }

    
export const getGetApiCategoryCountByStoreStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryCountByStoreStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>> = ({ signal }) => getApiCategoryCountByStoreStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryCountByStoreStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>>
export type GetApiCategoryCountByStoreStoreIdQueryError = unknown


export function useGetApiCategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryCountByStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryCountByStoreStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiCategoryExists = (
    params?: GetApiCategoryExistsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/Category/exists`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCategoryExistsQueryKey = (params?: GetApiCategoryExistsParams,) => {
    return [
    `/api/Category/exists`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCategoryExistsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryExists>>, TError = unknown>(params?: GetApiCategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryExists>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryExistsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryExists>>> = ({ signal }) => getApiCategoryExists(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryExists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryExistsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryExists>>>
export type GetApiCategoryExistsQueryError = unknown


export function useGetApiCategoryExists<TData = Awaited<ReturnType<typeof getApiCategoryExists>>, TError = unknown>(
 params: undefined |  GetApiCategoryExistsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryExists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryExists>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryExists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryExists<TData = Awaited<ReturnType<typeof getApiCategoryExists>>, TError = unknown>(
 params?: GetApiCategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryExists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryExists>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryExists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryExists<TData = Awaited<ReturnType<typeof getApiCategoryExists>>, TError = unknown>(
 params?: GetApiCategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryExists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryExists<TData = Awaited<ReturnType<typeof getApiCategoryExists>>, TError = unknown>(
 params?: GetApiCategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryExists>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryExistsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiCategoryHierarchyStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/Category/hierarchy/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryHierarchyStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/Category/hierarchy/${storeId}`
    ] as const;
    }

    
export const getGetApiCategoryHierarchyStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryHierarchyStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>> = ({ signal }) => getApiCategoryHierarchyStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryHierarchyStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>>
export type GetApiCategoryHierarchyStoreIdQueryError = unknown


export function useGetApiCategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryHierarchyStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryHierarchyStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiCategoryPagedList = (
    params?: GetApiCategoryPagedListParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResultCategoryCategoryDto>(
      {url: `/api/Category/paged/list`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCategoryPagedListQueryKey = (params?: GetApiCategoryPagedListParams,) => {
    return [
    `/api/Category/paged/list`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCategoryPagedListQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError = unknown>(params?: GetApiCategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryPagedListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryPagedList>>> = ({ signal }) => getApiCategoryPagedList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryPagedListQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryPagedList>>>
export type GetApiCategoryPagedListQueryError = unknown


export function useGetApiCategoryPagedList<TData = Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError = unknown>(
 params: undefined |  GetApiCategoryPagedListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryPagedList>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryPagedList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryPagedList<TData = Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError = unknown>(
 params?: GetApiCategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryPagedList>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryPagedList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryPagedList<TData = Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError = unknown>(
 params?: GetApiCategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryPagedList<TData = Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError = unknown>(
 params?: GetApiCategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryPagedList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryPagedListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiCategoryStoreStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/Category/store/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCategoryStoreStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/Category/store/${storeId}`
    ] as const;
    }

    
export const getGetApiCategoryStoreStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryStoreStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>> = ({ signal }) => getApiCategoryStoreStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryStoreStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>>
export type GetApiCategoryStoreStoreIdQueryError = unknown


export function useGetApiCategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryStoreStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1Category = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/v1/Category`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryQueryKey = () => {
    return [
    `/api/v1/Category`
    ] as const;
    }

    
export const getGetApiV1CategoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Category>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Category>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Category>>> = ({ signal }) => getApiV1Category(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Category>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Category>>>
export type GetApiV1CategoryQueryError = unknown


export function useGetApiV1Category<TData = Awaited<ReturnType<typeof getApiV1Category>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Category>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Category>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Category>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Category<TData = Awaited<ReturnType<typeof getApiV1Category>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Category>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Category>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Category>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Category<TData = Awaited<ReturnType<typeof getApiV1Category>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Category>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1Category<TData = Awaited<ReturnType<typeof getApiV1Category>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Category>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiV1Category = (
    categoryCreateCategoryDto: CategoryCreateCategoryDto,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDto>(
      {url: `/api/v1/Category`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateCategoryDto, signal
    },
      );
    }
  


export const getPostApiV1CategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Category>>, TError,{data: CategoryCreateCategoryDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Category>>, TError,{data: CategoryCreateCategoryDto}, TContext> => {

const mutationKey = ['postApiV1Category'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Category>>, {data: CategoryCreateCategoryDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Category(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CategoryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Category>>>
    export type PostApiV1CategoryMutationBody = CategoryCreateCategoryDto
    export type PostApiV1CategoryMutationError = unknown

    export const usePostApiV1Category = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Category>>, TError,{data: CategoryCreateCategoryDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Category>>,
        TError,
        {data: CategoryCreateCategoryDto},
        TContext
      > => {

      const mutationOptions = getPostApiV1CategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CategoryId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDto>(
      {url: `/api/v1/Category/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/Category/${id}`
    ] as const;
    }

    
export const getGetApiV1CategoryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryId>>> = ({ signal }) => getApiV1CategoryId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryId>>>
export type GetApiV1CategoryIdQueryError = unknown


export function useGetApiV1CategoryId<TData = Awaited<ReturnType<typeof getApiV1CategoryId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryId<TData = Awaited<ReturnType<typeof getApiV1CategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryId<TData = Awaited<ReturnType<typeof getApiV1CategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryId<TData = Awaited<ReturnType<typeof getApiV1CategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiV1CategoryId = (
    id: string,
    categoryUpdateCategoryDto: CategoryUpdateCategoryDto,
 ) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDto>(
      {url: `/api/v1/Category/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryUpdateCategoryDto
    },
      );
    }
  


export const getPutApiV1CategoryIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CategoryId>>, TError,{id: string;data: CategoryUpdateCategoryDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CategoryId>>, TError,{id: string;data: CategoryUpdateCategoryDto}, TContext> => {

const mutationKey = ['putApiV1CategoryId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CategoryId>>, {id: string;data: CategoryUpdateCategoryDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1CategoryId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CategoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CategoryId>>>
    export type PutApiV1CategoryIdMutationBody = CategoryUpdateCategoryDto
    export type PutApiV1CategoryIdMutationError = unknown

    export const usePutApiV1CategoryId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CategoryId>>, TError,{id: string;data: CategoryUpdateCategoryDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CategoryId>>,
        TError,
        {id: string;data: CategoryUpdateCategoryDto},
        TContext
      > => {

      const mutationOptions = getPutApiV1CategoryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteApiV1CategoryId = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Category/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1CategoryIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CategoryId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CategoryId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1CategoryId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CategoryId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1CategoryId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CategoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CategoryId>>>
    
    export type DeleteApiV1CategoryIdMutationError = unknown

    export const useDeleteApiV1CategoryId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CategoryId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CategoryId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CategoryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CategoryIdDetails = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseCategoryCategoryDetailDto>(
      {url: `/api/v1/Category/${id}/details`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryIdDetailsQueryKey = (id?: string,) => {
    return [
    `/api/v1/Category/${id}/details`
    ] as const;
    }

    
export const getGetApiV1CategoryIdDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryIdDetailsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>> = ({ signal }) => getApiV1CategoryIdDetails(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryIdDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>>
export type GetApiV1CategoryIdDetailsQueryError = unknown


export function useGetApiV1CategoryIdDetails<TData = Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryIdDetails<TData = Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryIdDetails<TData = Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryIdDetails<TData = Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryIdDetails>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryIdDetailsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchApiV1CategoryIdSoftDelete = (
    id: string,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Category/${id}/soft-delete`, method: 'PATCH'
    },
      );
    }
  


export const getPatchApiV1CategoryIdSoftDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CategoryIdSoftDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CategoryIdSoftDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiV1CategoryIdSoftDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1CategoryIdSoftDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiV1CategoryIdSoftDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1CategoryIdSoftDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1CategoryIdSoftDelete>>>
    
    export type PatchApiV1CategoryIdSoftDeleteMutationError = unknown

    export const usePatchApiV1CategoryIdSoftDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CategoryIdSoftDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1CategoryIdSoftDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPatchApiV1CategoryIdSoftDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchApiV1CategoryIdStatus = (
    id: string,
    params?: PatchApiV1CategoryIdStatusParams,
 ) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Category/${id}/status`, method: 'PATCH',
        params
    },
      );
    }
  


export const getPatchApiV1CategoryIdStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CategoryIdStatus>>, TError,{id: string;params?: PatchApiV1CategoryIdStatusParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CategoryIdStatus>>, TError,{id: string;params?: PatchApiV1CategoryIdStatusParams}, TContext> => {

const mutationKey = ['patchApiV1CategoryIdStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1CategoryIdStatus>>, {id: string;params?: PatchApiV1CategoryIdStatusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  patchApiV1CategoryIdStatus(id,params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1CategoryIdStatusMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1CategoryIdStatus>>>
    
    export type PatchApiV1CategoryIdStatusMutationError = unknown

    export const usePatchApiV1CategoryIdStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CategoryIdStatus>>, TError,{id: string;params?: PatchApiV1CategoryIdStatusParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1CategoryIdStatus>>,
        TError,
        {id: string;params?: PatchApiV1CategoryIdStatusParams},
        TContext
      > => {

      const mutationOptions = getPatchApiV1CategoryIdStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiV1CategoryParentIdSubcategories = (
    parentId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/v1/Category/${parentId}/subcategories`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryParentIdSubcategoriesQueryKey = (parentId?: string,) => {
    return [
    `/api/v1/Category/${parentId}/subcategories`
    ] as const;
    }

    
export const getGetApiV1CategoryParentIdSubcategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError = unknown>(parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryParentIdSubcategoriesQueryKey(parentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>> = ({ signal }) => getApiV1CategoryParentIdSubcategories(parentId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(parentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryParentIdSubcategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>>
export type GetApiV1CategoryParentIdSubcategoriesQueryError = unknown


export function useGetApiV1CategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryParentIdSubcategories<TData = Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError = unknown>(
 parentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryParentIdSubcategories>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryParentIdSubcategoriesQueryOptions(parentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CategoryActiveList = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/v1/Category/active/list`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryActiveListQueryKey = () => {
    return [
    `/api/v1/Category/active/list`
    ] as const;
    }

    
export const getGetApiV1CategoryActiveListQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryActiveListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>> = ({ signal }) => getApiV1CategoryActiveList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryActiveListQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>>
export type GetApiV1CategoryActiveListQueryError = unknown


export function useGetApiV1CategoryActiveList<TData = Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryActiveList>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryActiveList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryActiveList<TData = Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryActiveList>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryActiveList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryActiveList<TData = Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryActiveList<TData = Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryActiveList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryActiveListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CategoryCountByStoreStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseInt32>(
      {url: `/api/v1/Category/count/by-store/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryCountByStoreStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/v1/Category/count/by-store/${storeId}`
    ] as const;
    }

    
export const getGetApiV1CategoryCountByStoreStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryCountByStoreStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>> = ({ signal }) => getApiV1CategoryCountByStoreStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryCountByStoreStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>>
export type GetApiV1CategoryCountByStoreStoreIdQueryError = unknown


export function useGetApiV1CategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryCountByStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryCountByStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryCountByStoreStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CategoryExists = (
    params?: GetApiV1CategoryExistsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseBoolean>(
      {url: `/api/v1/Category/exists`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CategoryExistsQueryKey = (params?: GetApiV1CategoryExistsParams,) => {
    return [
    `/api/v1/Category/exists`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CategoryExistsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError = unknown>(params?: GetApiV1CategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryExistsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryExists>>> = ({ signal }) => getApiV1CategoryExists(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryExistsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryExists>>>
export type GetApiV1CategoryExistsQueryError = unknown


export function useGetApiV1CategoryExists<TData = Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError = unknown>(
 params: undefined |  GetApiV1CategoryExistsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryExists>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryExists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryExists<TData = Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError = unknown>(
 params?: GetApiV1CategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryExists>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryExists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryExists<TData = Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError = unknown>(
 params?: GetApiV1CategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryExists<TData = Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError = unknown>(
 params?: GetApiV1CategoryExistsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryExists>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryExistsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CategoryHierarchyStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/v1/Category/hierarchy/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryHierarchyStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/v1/Category/hierarchy/${storeId}`
    ] as const;
    }

    
export const getGetApiV1CategoryHierarchyStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryHierarchyStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>> = ({ signal }) => getApiV1CategoryHierarchyStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryHierarchyStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>>
export type GetApiV1CategoryHierarchyStoreIdQueryError = unknown


export function useGetApiV1CategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryHierarchyStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryHierarchyStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryHierarchyStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CategoryPagedList = (
    params?: GetApiV1CategoryPagedListParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponsePaginatedResultCategoryCategoryDto>(
      {url: `/api/v1/Category/paged/list`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1CategoryPagedListQueryKey = (params?: GetApiV1CategoryPagedListParams,) => {
    return [
    `/api/v1/Category/paged/list`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1CategoryPagedListQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError = unknown>(params?: GetApiV1CategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryPagedListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>> = ({ signal }) => getApiV1CategoryPagedList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryPagedListQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>>
export type GetApiV1CategoryPagedListQueryError = unknown


export function useGetApiV1CategoryPagedList<TData = Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError = unknown>(
 params: undefined |  GetApiV1CategoryPagedListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryPagedList>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryPagedList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryPagedList<TData = Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError = unknown>(
 params?: GetApiV1CategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryPagedList>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryPagedList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryPagedList<TData = Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError = unknown>(
 params?: GetApiV1CategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryPagedList<TData = Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError = unknown>(
 params?: GetApiV1CategoryPagedListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryPagedList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryPagedListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiV1CategoryStoreStoreId = (
    storeId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ApiResponseIEnumerableCategoryCategoryDto>(
      {url: `/api/v1/Category/store/${storeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CategoryStoreStoreIdQueryKey = (storeId?: string,) => {
    return [
    `/api/v1/Category/store/${storeId}`
    ] as const;
    }

    
export const getGetApiV1CategoryStoreStoreIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError = unknown>(storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CategoryStoreStoreIdQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>> = ({ signal }) => getApiV1CategoryStoreStoreId(storeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CategoryStoreStoreIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>>
export type GetApiV1CategoryStoreStoreIdQueryError = unknown


export function useGetApiV1CategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CategoryStoreStoreId<TData = Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError = unknown>(
 storeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CategoryStoreStoreId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CategoryStoreStoreIdQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




