/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietCommerce Admin API
 * VietCommerce Admin Management API - Comprehensive API for managing products, orders, inventory, marketing posts, and administrative operations.
        
**Authentication:**
All endpoints (except analytics endpoints) require JWT Bearer token authentication with Admin role.

**Marketing Post Management:**
- Create, update, delete, and restore marketing posts
- Publish, schedule, and unpublish posts
- Track analytics (views, clicks, shares)
- Bulk operations for efficient management
- Link posts to products for targeted marketing

**Key Features:**
- Soft delete with restore capability
- Priority scoring for display control (1-100)
- Multi-platform social media variants
- SEO metadata management
- Comprehensive filtering and search
- Real-time analytics tracking
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiShiftsParams,
  HRMCloseShiftRequest,
  HRMOpenShiftRequest,
  HRMUpdateShiftRequest
} from '.././schemas';

import { apiClient } from '../../../src/lib/api/orval-client';




export const getApiShifts = (
    params?: GetApiShiftsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/Shifts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiShiftsQueryKey = (params?: GetApiShiftsParams,) => {
    return [
    `/api/Shifts`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiShiftsQueryOptions = <TData = Awaited<ReturnType<typeof getApiShifts>>, TError = unknown>(params?: GetApiShiftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShiftsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShifts>>> = ({ signal }) => getApiShifts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShiftsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShifts>>>
export type GetApiShiftsQueryError = unknown


export function useGetApiShifts<TData = Awaited<ReturnType<typeof getApiShifts>>, TError = unknown>(
 params: undefined |  GetApiShiftsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShifts>>,
          TError,
          Awaited<ReturnType<typeof getApiShifts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShifts<TData = Awaited<ReturnType<typeof getApiShifts>>, TError = unknown>(
 params?: GetApiShiftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShifts>>,
          TError,
          Awaited<ReturnType<typeof getApiShifts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShifts<TData = Awaited<ReturnType<typeof getApiShifts>>, TError = unknown>(
 params?: GetApiShiftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShifts<TData = Awaited<ReturnType<typeof getApiShifts>>, TError = unknown>(
 params?: GetApiShiftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShiftsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getApiShiftsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/Shifts/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiShiftsIdQueryKey = (id?: string,) => {
    return [
    `/api/Shifts/${id}`
    ] as const;
    }

    
export const getGetApiShiftsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiShiftsId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShiftsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShiftsId>>> = ({ signal }) => getApiShiftsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShiftsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShiftsId>>>
export type GetApiShiftsIdQueryError = unknown


export function useGetApiShiftsId<TData = Awaited<ReturnType<typeof getApiShiftsId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShiftsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShiftsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShiftsId<TData = Awaited<ReturnType<typeof getApiShiftsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShiftsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShiftsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShiftsId<TData = Awaited<ReturnType<typeof getApiShiftsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShiftsId<TData = Awaited<ReturnType<typeof getApiShiftsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShiftsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putApiShiftsId = (
    id: string,
    hRMUpdateShiftRequest: HRMUpdateShiftRequest,
 ) => {
      
      
      return apiClient<void>(
      {url: `/api/Shifts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: hRMUpdateShiftRequest
    },
      );
    }
  


export const getPutApiShiftsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiShiftsId>>, TError,{id: string;data: HRMUpdateShiftRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiShiftsId>>, TError,{id: string;data: HRMUpdateShiftRequest}, TContext> => {

const mutationKey = ['putApiShiftsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiShiftsId>>, {id: string;data: HRMUpdateShiftRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiShiftsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiShiftsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiShiftsId>>>
    export type PutApiShiftsIdMutationBody = HRMUpdateShiftRequest
    export type PutApiShiftsIdMutationError = unknown

    export const usePutApiShiftsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiShiftsId>>, TError,{id: string;data: HRMUpdateShiftRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiShiftsId>>,
        TError,
        {id: string;data: HRMUpdateShiftRequest},
        TContext
      > => {

      const mutationOptions = getPutApiShiftsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiShiftsCloseId = (
    id: string,
    hRMCloseShiftRequest: HRMCloseShiftRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/Shifts/close/${id}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hRMCloseShiftRequest, signal
    },
      );
    }
  


export const getPostApiShiftsCloseIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShiftsCloseId>>, TError,{id: string;data: HRMCloseShiftRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiShiftsCloseId>>, TError,{id: string;data: HRMCloseShiftRequest}, TContext> => {

const mutationKey = ['postApiShiftsCloseId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiShiftsCloseId>>, {id: string;data: HRMCloseShiftRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiShiftsCloseId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiShiftsCloseIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiShiftsCloseId>>>
    export type PostApiShiftsCloseIdMutationBody = HRMCloseShiftRequest
    export type PostApiShiftsCloseIdMutationError = unknown

    export const usePostApiShiftsCloseId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShiftsCloseId>>, TError,{id: string;data: HRMCloseShiftRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiShiftsCloseId>>,
        TError,
        {id: string;data: HRMCloseShiftRequest},
        TContext
      > => {

      const mutationOptions = getPostApiShiftsCloseIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getApiShiftsCurrentUserId = (
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/Shifts/current/${userId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiShiftsCurrentUserIdQueryKey = (userId?: string,) => {
    return [
    `/api/Shifts/current/${userId}`
    ] as const;
    }

    
export const getGetApiShiftsCurrentUserIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError = unknown>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShiftsCurrentUserIdQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>> = ({ signal }) => getApiShiftsCurrentUserId(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShiftsCurrentUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>>
export type GetApiShiftsCurrentUserIdQueryError = unknown


export function useGetApiShiftsCurrentUserId<TData = Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError = unknown>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShiftsCurrentUserId<TData = Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShiftsCurrentUserId<TData = Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShiftsCurrentUserId<TData = Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsCurrentUserId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShiftsCurrentUserIdQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiShiftsOpen = (
    hRMOpenShiftRequest: HRMOpenShiftRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/Shifts/open`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hRMOpenShiftRequest, signal
    },
      );
    }
  


export const getPostApiShiftsOpenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShiftsOpen>>, TError,{data: HRMOpenShiftRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiShiftsOpen>>, TError,{data: HRMOpenShiftRequest}, TContext> => {

const mutationKey = ['postApiShiftsOpen'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiShiftsOpen>>, {data: HRMOpenShiftRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiShiftsOpen(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiShiftsOpenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiShiftsOpen>>>
    export type PostApiShiftsOpenMutationBody = HRMOpenShiftRequest
    export type PostApiShiftsOpenMutationError = unknown

    export const usePostApiShiftsOpen = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShiftsOpen>>, TError,{data: HRMOpenShiftRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiShiftsOpen>>,
        TError,
        {data: HRMOpenShiftRequest},
        TContext
      > => {

      const mutationOptions = getPostApiShiftsOpenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    